### ISSUE TITLE
Another problem with mode=link

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#101]
http://api.freme-project.eu/0.6/e-entity/freme-ner/documents?input=Germany&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=link

does not produce a link. When I tested a similar request in #87 this worked so it seems to be a new bug.

This issue is the same as freme-project/pipelines#21

Maybe the bug was introduced by https://github.com/freme-project/freme-ner/issues/94 ?

**Comment by m1ci** [comment]
can you please double-check if the `mode` parameter implemented in the endpoint of the new architecture?

**Comment by ArneBinder** [comment]
@m1ci thank you very muich for the hint, mode=link was really not (never) implemneted in the new architecture.
This should be fixed, but I was not able to do any testing from home, so I created the branch `mode-domain-types`. Furthermore this fixes another bug: the parameter `domain` and `types` were not used at all. Now the (domain-)restricted types are passed to EntityLinker.SpotLinkEntities / EntityLinker.LinkEntities.
@jnehring could you do some testing and merge this into the master? Or we wait until monday, when I'm back in the office.

**Comment by m1ci** [comment]
@ArneBinder thanks for the catch and fixes!

**Comment by ArneBinder** [comment]
The domains parameter is still not working, see #106.

**Comment by ArneBinder** [comment]
Linking of plain text works at dev, try [this](http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Germany&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=link).

```
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .

<http://freme-project.eu/#char=0,7>
        a                     nif:Phrase , nif:Word , nif:String , nif:RFC5147String , nif:Context ;
        nif:anchorOf          "Germany"^^xsd:string ;
        nif:beginIndex        "0"^^xsd:int ;
        nif:endIndex          "7"^^xsd:int ;
        nif:isString          "Germany"^^xsd:string ;
        nif:referenceContext  <http://freme-project.eu/#char=0,7> ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Germany> .
```

The linking question moved to #104, so can we close this?

**Comment by jnehring** [comment]
I tested it, it works.
