### ISSUE TITLE
NIF input format for mode=link

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#104]
While working on #101 we found an unexpected behaviour with mode=link: When I do named entity enrichment with mode=spot,classify and put the output of this to mode=link then I do not get any links. According to #87 the content nif:isString will be linked. But FREME NER puts the annotations in the nif:anchorOf property and there this cannot be enriched. Further we found out that in the original FREME NER before the architecture update, it was not possible to use mode=link for NIF, it was possible to use mode=link when the input format was plaintext.

I think that mode=link should link named entity annotations only. So when we use this in a larger pipeline not every annotation should be linked. But how do we spot named entity annotations? I think we can recognize this only when the annotation has a itsrdf:taConfidence attribute.

@m1ci do you also think linking nif:isString is not a good idea? And what do you think about linking only named entity annotations?

```
@prefix xsd:   
<http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: 
    <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   
        <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .


            <http://freme-project.eu/#char=11,17>
        a                     nif:RFC5147String , nif:String , nif:Phrase , nif:Word ;
        nif:anchorOf          "Berlin"^^xsd:string ;
        nif:beginIndex        "11"^^xsd:int ;
        nif:endIndex          "17"^^xsd:int ;
        nif:referenceContext  
                <http://freme-project.eu/#char=0,59> ;
        itsrdf:taConfidence   "0.9462878262776647"^^xsd:double .


                    <http://freme-project.eu/#char=0,59>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "59"^^xsd:int ;
        nif:isString    "Welcome to Berlin!^^http://www.w3.org/2001/XMLSchema#string"^^xsd:string .
```

**Comment by m1ci** [comment]
> I think that mode=link should link named entity annotations only.

true.

There are two ways that you can do linking:
1) linking single entity mentions
Example: when client sets informat=text, mode=link and input=Argentina -> FREME NER will link this single entity.

This works. Try
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Argentina.&outformat=turtle&language=en&dataset=dbpedia&mode=link

2) linking of multiple mentions
User submits NIF with entity mentions encoded as nif:anchorOf
In this case, informat is RDF (not text),
Here linking is done for every `nif:anchorOf` string.

For unknown reason this does not work (was working before the arch update).

Hope its more clear now.

**Comment by jox** [comment]
We also came across this. The problem with mode=link is, that a new RDF model is created not matter what informat is given. In case of NIF input, the created RDF model will contain only the isString of the input NIF. The rest of the input is dropped and lost.

See the pull request that fixes that. It will create a new RDF model only in case of plain text input. Otherwise the input NIF is passed to the linking.

**Comment by ArneBinder** [comment]
@m1ci this seems to work again. Can we close it?

**Comment by m1ci** [comment]
yup
