### ISSUE TITLE
enrich only nif:isString

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#105]
This API call

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=de&dataset=dbpedia&informat=turtle&mode=link

with body

```
@prefix xsd:   
<http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: 
    <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   
        <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .


                        <http://freme-project.eu/#char=0,18>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "18"^^xsd:int ;
        nif:isString    "Welcome to Berlin!"^^xsd:string .
```

Produces

```
@prefix xsd:   
<http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: 
    <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   
        <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .


            <http://freme-project.eu/#char=0,59>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "59"^^xsd:int ;
        nif:isString    "Welcome to Berlin!^^http://www.w3.org/2001/XMLSchema#string"^^xsd:string .
```

The nif:isString of the result is wrong - the nif source code went inside of the plaintext.

**Comment by m1ci** [comment]
There are two issues:
  - you have set wrong language, instead of `en` you use `de` 
  -  you use mode=link but no entity annotation in the input

**Comment by jnehring** [comment]
> you have set wrong language, instead of en you use de
right
> you use mode=link but no entity annotation in the input
See discussion in #104. According to #87 my NIF is correct.

This issue is more about the bug in this line:

```
        nif:isString    "Welcome to Berlin!^^http://www.w3.org/2001/XMLSchema#string"^^xsd:string .
```

This is not FREME NER specific, this can also also happen in other e-services.

**Comment by ArneBinder** [comment]
The problem was located just in FremeNer, not in FREMECommon (as supposed before).
