### ISSUE TITLE
Analyze the code

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#107]
Please go through the codes of [FREME NER](https://github.com/freme-project/freme-ner) and draw a diagram of how it works.

**Comment by bgrusdt** [comment]
![fremener grafik](https://cloud.githubusercontent.com/assets/19168976/18057394/1d0461c6-6e10-11e6-8917-e9e369778e90.jpg)

**Comment by jnehring** [comment]
Thank you! Please move the original image here: https://drive.google.com/drive/folders/0B8CeKhHCOSqUVHRUTXNjSl94RXc

**Comment by jnehring** [comment]
Please add the image to https://freme-project.github.io/knowledge-base/freme-for-api-users/freme-ner.html . Please rename section "FREME NER on GitHub" to "Working with the FREME NER source code" and adjust the text if necessary. Add the image to this chapter.

**Comment by bgrusdt** [comment]
I added the image to the google drive folder and to the [dev - documentation](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#working-with-the-freme-ner-source-code).
