### ISSUE TITLE
Custom vocabulary to be transformed into SKOS

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/freme-ner#110]
Hello @m1ci,

we would like to perform entity linking through the FREME CKEditor plugin on a custom dataset. I understand that we have to transform it into SKOS, with which I'm pretty much unfamiliar. Could you please help?

The dataset has been provided to us in CSV format and follows the following structure:
`Term name; Term link; Term description;`

Thank you very much in advance!

[GWPP_Glossary.zip](https://github.com/freme-project/freme-ner/files/291494/GWPP_Glossary.zip)

**Comment by m1ci** [comment]
@Katsivelisp can you send CSV which will include only the label and the link?
I tried to parse the CSV but I could not manage to parse it properly - there are new lines in the description field which makes the parsing difficult. I also could not manage to import it even in Excel.

**Comment by Katsivelisp** [comment]
@m1ci Here it is:
[GWPP_Glossary.zip](https://github.com/freme-project/freme-ner/files/295334/GWPP_Glossary.zip)

**Comment by Katsivelisp** [comment]
Hello again @m1ci ,

any news on this?

**Comment by m1ci** [comment]
Done, the dataset has been converted and integrated in the FREME NER (dev API) with ID `gwpp-glossary`

@Katsivelisp should I load it in the live API?

Here is a call example:

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=A%20text%20with%20some%20glossary%20terms,%20such%20as%20Capsid%20proteins%20and%20Adenoviral%20keratoconjunctivitis.&outformat=turtle&language=en&dataset=gwpp-glossary

**Comment by Katsivelisp** [comment]
@m1ci I would say, let us try it first and we'll see.

**Comment by Katsivelisp** [comment]
Hello again @m1ci,

could you please load it in the live API? We need to run some tests with the CKEditor Plugin and it requires a stable version of the API.

Thank you very much!

**Comment by m1ci** [comment]
done, see
http://api.freme-project.eu/current/e-entity/freme-ner/datasets/gwpp-glossary?outformat=json

**Comment by Katsivelisp** [comment]
Thanks @m1ci ! :)

**Comment by Katsivelisp** [comment]
Hello @m1ci,

could you please re-upload this dataset for us (newer version)?
[GWPP-glossary.zip](https://github.com/freme-project/freme-ner/files/357212/GWPP-glossary.zip)
