### ISSUE TITLE
linkingMethod parameter

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#112]
Some time ago we experimented with an additional approach for entity linking. It was designed on request from AK (\cc @Katsivelisp)
The parameter that has been implemented had name `linkingMethod` and so far the only possible value was/is `SurfaceFormSimilarity1`

This effort significantly improved the performance of the linking in terms of precision with low number of false positives.

This feature was implemented and was working on FREME dev.
@jnehring can you please check why this is not working in the API with with new arch update?

Adding @Katsivelisp and @sandroacoelho into the loop

**Comment by m1ci** [comment]
this is what the @Katsivelisp was asking in https://github.com/freme-project/freme-ner/issues/112

**Comment by jnehring** [comment]
I did not know about this parameter. Also the functionality is not clear to me. When there is only one parameter value, then this parameter is always set. Also what are the two linking methods? There is no documentation about the linking methods and about the parameter.

Further the parameter is not included in the FREME java / scala bridge: https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/api/java/FremeNer.java I can pass on the parameter only when it is in the bridge.

**Comment by m1ci** [comment]
> Also what are the two linking methods?

One is based on the most-frequent-sense (MFS) (by default) the other is based on the surface form similarity.

> Further the parameter is not included in the FREME java / scala bridge: https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/api/java/FremeNer.java I can pass on the parameter only when it is in the bridge.

@sandroacoelho can you take care of this please?

**Comment by sandroacoelho** [comment]
Hi @m1ci ,

I re-implemented the changes that were in develop branch. There is a slightly change in order to do not change the REST API. 

How to use it? Just fill in the property freme.ner.linkingMethod in application.properties with SurfaceFormSimilarity1 to enable this filter.

todo list:
- [ ] Write test case  (Could you please remind me a case for this problem ? )

**Current mvn test output status**
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0

**Comment by jnehring** [comment]
One more todo: Please create an issue in the [Documentation repository](https://github.com/freme-project/Documentation/issues) and describe this parameter. Then assign it to @bgrusdt she will add your explanations to the API documentation. I think it also makes sense to write a few lines about the parameter in the [FREME NER documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html).

**Comment by sandroacoelho** [comment]
Linking Method (linkingMethod) is a configurable parameter that aims to add extras approaches on entity linking step to improve recall. In NER systems, recall is similarly the number of names in the gold standard that appear at exactly the same location in the predictions.


FREME-NER provides the following approaches to leverage the recall:

-  **SurfaceFormSimilarity1**: leaning on Jaro–Winkler string similarity/distance, FREME-NER computes a distance between selected entities in Solr and the annotated entities;

**Comment by jnehring** [comment]
Because of the documentation I created https://github.com/freme-project/Documentation/issues/279

About the implementation: What exactly did you implement? Apart from being implemented on the inside of FREME NER it needs to be implemented in (correct me if Im wrong):

* The [Java / Scala bridge](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/api/java/FremeNer.java). There was no change in this file for three weeks. It is necessary that you implement this in the bridge.
* The [REST API](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerEnrichment.java). I cannot see this change. DFKI / @bgrusdt can perform this task when the java /scala bridge is ready.

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

It is just a [filter](https://github.com/freme-project/freme-ner/blob/master/src/main/scala/org/elinker/core/api/filter/SimilarityFilter.scala) that uses freme.ner.linkingMethod property loaded at FREME-NER startup. 

@m1ci has requested to me in ASANA:
> The linkingMethod parameter that you implemented some time ago is not working. Can you please check what is the issue? it might not be implemented in the REST API for FREME NER.

Should I refactor it to put in REST API?

Best,

**Comment by m1ci** [comment]
> Should I refactor it to put in REST API?

It sounds the parameter is not implemented in the REST API and Scala/Java bridge, so please do.

**Comment by jnehring** [comment]
Please integrate it in the Scala bridge. DFKI can integrate it in the REST API.

**Comment by sandroacoelho** [comment]
ok... Let's do it.

Best,

**Comment by m1ci** [comment]
what is the status of this task?

**Comment by jnehring** [comment]
@sandroacoelho what is the status?

**Comment by sandroacoelho** [comment]
Hi @m1ci , @jnehring : It's done.

Best,

**Comment by jnehring** [comment]
I tested the two different methods and got exactly the same results. I would assume that at least the confidence values differ. Below you can see my tests, the first three detected entities and their confidence values.

### With linkingMethod=SurfaceFormSimilarity1

```
curl -X POST -H "Content-Type: text/plain" -H "Accept: text/turtle" -H "Cache-Control: no-cache" -H "Postman-Token: 4c5d6b00-1b52-7304-def4-9d700995d2d8" -d 'The Eiffel Tower (/ˈaɪfəl ˈtaʊər/ EYE-fəl TOWR; French: tour Eiffel [tuʁ‿ɛfɛl] About this sound listen) is a wrought iron lattice tower on the Champ de Mars in Paris.' "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&linkingMethod=SurfaceFormSimilarity1"
```
itsrdf:taIdentRef     <http://dbpedia.org/resource/Eiffel> .
itsrdf:taConfidence   "0.7495701895074838"^^xsd:double ;

itsrdf:taIdentRef     <http://dbpedia.org/resource/Paris> .
itsrdf:taConfidence   "0.9612433574290751"^^xsd:double ;

itsrdf:taIdentRef     <http://dbpedia.org/resource/French> .
itsrdf:taConfidence   "0.9966307142440672"^^xsd:double ;


### Without linkingMethod parameter

```
curl -X POST -H "Content-Type: text/plain" -H "Accept: text/turtle" -H "Cache-Control: no-cache" -H "Postman-Token: d82d9bbc-283e-9048-077e-f1864c555f70" -d 'The Eiffel Tower (/ˈaɪfəl ˈtaʊər/ EYE-fəl TOWR; French: tour Eiffel [tuʁ‿ɛfɛl] About this sound listen) is a wrought iron lattice tower on the Champ de Mars in Paris.' "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"
```

itsrdf:taIdentRef     <http://dbpedia.org/resource/Eiffel> .
itsrdf:taConfidence   "0.7495701895074838"^^xsd:double ;

itsrdf:taIdentRef     <http://dbpedia.org/resource/Paris> .
itsrdf:taConfidence   "0.9612433574290751"^^xsd:double ;
  
itsrdf:taIdentRef     <http://dbpedia.org/resource/French> .
itsrdf:taConfidence   "0.9966307142440672"^^xsd:double ;

**Comment by m1ci** [comment]
these confidence values are the one returned by StanfordNER, (spotting+classification), confidence for linking is not returned since its difficult to normalize and return meaningful values.

**Comment by m1ci** [comment]
however, itsrdf:taConfidence is very generic, thus NIF 2.1 introduces more fine grained properties:
nif:taIdentConf - for linking confidence
nif:taClassConf - for typing confidence
nif:entityOccurrenceConf - for spotting confidence

Should we consider using those? @jnehring

**Comment by jnehring** [comment]
Lets discuss this on next dev call. I know that at least WRIPL uses itsrdf:taConfidence.

**Comment by jnehring** [comment]
Maybe we should not change this. No partner has asked for other confidence values so I think there is no reason to change this.

**Comment by m1ci** [comment]
the issue is fixed, and there is no active discussion, closing the issue
