### ISSUE TITLE
Make datasets available

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#114]
In case we want to make the FREME NER datasets available to others, what do we need to do? With making them available I mean that other FREME users like the ADAPT research centre can easily upload our datasets into their FREME NER installation?

I guess we need to provide the SKOS files for these datasets. It would also be nice to have an installer script.

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

For the data, we have two options: 
-  Prepare a small script that reads our index and generate a dump to be imported or
- Turn our index available to download in binary format ( Solr/Lucene format) 

What about to delivery all FREME solution through docker composer (Broker, Link , Publish, NER,Solr etc) ?

**Comment by m1ci** [comment]
I like the idea to provide FREME as docker

> Prepare a small script that reads our index and generate a dump to be imported or
> Turn our index available to download in binary format ( Solr/Lucene format)

Isnt it better to have a script-per-dataset which loads the data into Solr via FREME NER?

**Comment by sandroacoelho** [comment]
Hi @m1ci , @jnehring 

We can use a simple shell script to do this dirty job for us. Is also possible to split the dump by dataset as Milan suggested

Please take a look [on this snippet](https://gist.github.com/sandroacoelho/00ef674f19f047a2a5574b2e6d8da410)

**Comment by m1ci** [comment]
thanks @sandroacoelho for this. Sharing dumps is fine, however, the source dataset can evolve over the time and we might want to integrate it from scratch. My idea was to have script-per-dataset such as
https://github.com/freme-project/freme-ner/blob/master/index-loc-authors.py
which loads RDF into Solr via FREME NER.
The execution of all these scripts can be triggered by one single bash script.

**Comment by jnehring** [comment]
In last developers call we agreed on creating a shell script for each dataset.

**Comment by sandroacoelho** [comment]
Hi @jnehring, @m1ci 

We have two shell scripts to do this job for us, as follow:
- [freme-ner-dump.sh](https://github.com/freme-project/freme-ner/blob/master/script/freme-ner-dump.sh) : extracts all non-DBpedia datasets in chunks of 1000000
- [freme-ner-dump-to-dataset.sh] (https://github.com/freme-project/freme-ner/blob/master/script/freme-ner-dump-to-dataset.sh): read and categorizes all dump files by dataset / language

I can say that freme-ner-dump-to-dataset.sh is in Beta version.  I have been facing some problems to deal with single quotes, quotes and some others special characters in label fields that I hope to solve ASAP. 

Our first extraction are available [here](https://www.dropbox.com/sh/c4otelnrga249g6/AAAwepRh3ObZz4lWk2tTVJJca?dl=0). 

Best,

**Comment by jnehring** [comment]
Thank you! I think the script reads the datasets that are currently in freme-ner and then creates dumps of these scripts. Am I right?

One more question: Why did you exclude DBPedia?

I think the next steps are

* Upload these datasets to our FREME server (I will do this as soon as all datasets are ready)
* Create a script that uploads all datasets.
* Write an article about how to upload a dataset, maybe with a reference to [this script](https://github.com/munnellg/freme_datasets). This article will cover also #125 later.

**Comment by sandroacoelho** [comment]
Hi  @jnehring 

>> Thank you! I think the script reads the datasets that are currently in freme-ner and then creates dumps of these scripts. Am I right?

Yes.

>> One more question: Why did you exclude DBPedia?

We can download DBpedia labels dataset from [here](http://wiki.dbpedia.org/Downloads2015-10), but if you think that is important to include this data in our dump, please let me know. I will just remove a [parameter in the query](https://github.com/freme-project/freme-ner/blob/master/script/freme-ner-dump.sh#L4)

>>I think the next steps are

>>Upload these datasets to our FREME server (I will do this as soon as all datasets are ready)
>>Create a script that uploads all datasets together, maybe using this script.
>>Write an article about how to upload a datase. This article will cover also #125 later.

Great. Before you start, give me a chance to finish a [docker for our Solr instance](https://github.com/sandroacoelho/freme-docker) . There we have a [tested solution for](https://github.com/sandroacoelho/freme-docker/blob/master/freme-ner-solr/conf/schema.xml#L276) our issue #91

Best,

**Comment by jnehring** [comment]
The datasets will be uploaded in #130.

**Comment by jnehring** [comment]
One question: The datasets you created, are they any different from the datasets already available at http://api.freme-project.eu/doc/current/api-doc/list-datasets.html ?

**Comment by m1ci** [comment]
what do you mean by different?
Btw, there is also:
- loc-authors (used by wripl) - The Library of Congress datasets provides author names.
- europeana (used by iMinds) - Europeana.eu is an internet portal that acts as an interface to millions of books, paintings, films, museum objects and archival records that have been digitised throughout Europe.
- gwpp-glossary (used by AK) - A custom vocabulary.

**Comment by jnehring** [comment]
> what do you mean by different?

I was afraid that the work done in this task was unnecessary. But now I see that there are some datasets that would not be available without this work.
