### ISSUE TITLE
 I can't upload a custom dataset

### ISSUE THREAD

**Issue by dimasaber** [freme-project/freme-ner#115]
**Scenario:**
1. Create a new user 
http://api.freme-project.eu/doc/0.5/api-doc/full.html#!/User/post_user
2. Authenticate to get user id (token)
http://api.freme-project.eu/doc/0.5/api-doc/full.html#!/User/post_authenticate
3. Try to upload a dataset with the following inputs (http://api.freme-project.eu/doc/0.5/api-doc/full.html#!/e-Entity/createDataset)
Enter any details. We can try it with an empty dataset
4. Press "Try it out!"

**Expected output:**
1. There is a way to add my token for authentication
2. The dataset is uploaded successfully
{
  "id" : 87,
  "creationTime" : 1466158777824,
  "description" : "This is for testing an authentication issue",
  "owner" : {
    "name" : "dima",
    "role" : "ROLE_USER"
  },
  "visibility" : "PUBLIC",
  "name" : "test1",
  "totalEntities" : 0
}

**Actual output:**
1. Curl command:
curl -X POST --header "Content-Type: text/n3" --header "Accept: application/json" -d "   \"101 Communications\" .
   \"101 Communications, Inc\" .
   \"101 Communications, LLC\" .
   \"101communications\" .
   \"2Cs Communications\" .
   \"2x4 (Design studio)\" .
 " "http://api.freme-project.eu/current/e-entity/freme-ner/datasets?informat=turtle&name=test1&description=This%20is%20for%20testing%20an%20authentication%20issue&language=en"
 
 2. Response body:
 {
  "exception": "eu.freme.common.exception.AccessDeniedException",
  "path": "/e-entity/freme-ner/datasets",
  "message": "Access denied",
  "error": "Unauthorized",
  "status": 401,
  "timestamp": 1466157199402
}

**Workaround:**
Take the curl command and update it (like follows), then run it from the command line.

curl -X POST --header "X-Auth-Token: 388ca555-c43d-4222-b42e-c7cb47958cac" --header "Content-Type: text/n3" --header "Accept: application/json" "http://api.freme-project.eu/current/e-entity/freme-ner/datasets?informat=turtle&name=test1&description=This%20is%20for%20testing%20an%20authentication%20issue&language=en"

**Comment by jnehring** [comment]
One thing I can see is that the dataset is not correct. I think it was generated via our API documentation which sometimes creates faulty CURL commands. It is better to put the dataset in a file and append it to the call using `-d "@dataset.nt"`.

But still the API call does not work. I get request timed out. @m1ci @sandroacoelho do you have an idea what is wrong with this curl request?

```
curl -v -d @dataset.txt "http://api.freme-project.eu/current/e-entity/freme-ner/datasets?name=NAME&description=DATASET_DESCRIPTION&informat=n-triples&outformat=json&language=en&token=388ca555-c43d-4222-b42e-c7cb47958cac" -H "Content-Type: application/n-triples"
```

with [dataset.txt](https://github.com/freme-project/freme-ner/files/320407/dataset.txt)

**Comment by m1ci** [comment]
I try
curl -v -d @dataset.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?name=NAME&description=DATASET_DESCRIPTION&informat=n-triples&outformat=json&language=en&token=YOUR_TOKEN" -H "Content-Type: application/n-triples"

and it works, the results are:

{
  "id" : 124,
  "creationTime" : 1466415926248,
  "description" : "DATASET_DESCRIPTION",
  "owner" : {
    "name" : "infai",
    "role" : "ROLE_USER"
  },
  "visibility" : "PUBLIC",
  "name" : "NAME",
  "totalEntities" : 6
}

**Comment by dimasaber** [comment]
Still in all cases there is no way to add your token while using the web service. I have to get the command, edit and run it from command line.
Right?

**Comment by m1ci** [comment]
the token you provide as query parameter. If you want to provide the token via the API docs, this is possible - at the end of http://api-dev.freme-project.eu/doc/api-doc/full.html there is token field, see:

> You can reuse your access token from /authenticate to stay authenticated for all further requests:

**Comment by m1ci** [comment]
@dimasaber did you manage to upload dataset?

**Comment by m1ci** [comment]
@dimasaber ping. Any update here?

**Comment by dimasaber** [comment]
Now yes. Thanks and sorry for the late reply
