### ISSUE TITLE
reactivate scala server

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-ner#116]
@m1ci proposed the following:
> Regarding the commented code that we discussed in https://github.com/freme-project/freme-ner/issues/106#issuecomment-227175489

> The code was unused in FREME but the code is actual embedded server which runs FREME NER as stand alone API - no dependency on FREME.

> We believe some would benefit from it and we would like to maintain this embedded Scala server.
> Can we roll back and uncomment the code? In order to avoid confusion we can provide some more  detailed comments inline the code.

@jnehring Should we do so? I dont know how complex this will be and if we do this we should clearly untangle the server functionality from the rest of freme-ner (putting all in an independent folder `standalone-server` e.g.). The most of the code was just commented, [here](https://github.com/freme-project/freme-ner/blob/72cac85189bd269e9486fb843e0252791abcffff/src/main/scala/org/elinker/core/api/service/DatasetApiService.scala) you can find the missing DatasetApiService. But I'm not sure if the code works still fine with the modifications done so far and if we would not get a bunch of redundant code (which leads to inconsistencies and errors in my opinion).
@m1ci but if you are sure that this will result in some benefits, feel free to re-add the code.

**Comment by sandroacoelho** [comment]
Hi @ArneBinder: I agree with you. Let's do a little more: I removed all unused code just to keep clear. I just asked because I did not know that you were modifying the architecture.  Thanks for the reply
