### ISSUE TITLE
API: request available datasets

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-ner#117]

**Comment by m1ci** [comment]
what is this issue about?

**Comment by pheyvaer** [comment]
That we can ask through the API which dataset are loaded in FREME NER, so, e.g., in a GUI we can list them to the users and they can select the one they want to use.

**Comment by m1ci** [comment]
this is already available, see
http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/getAllDatasets

**Comment by pheyvaer** [comment]
Aah OK, my bad! (cc @bjdmeest )
