### ISSUE TITLE
types parameter results in strange output

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-ner#118]
When I set the **types** parameter to ```http%3A%2F%2Fdbpedia.org%2Fontology%2FLocation``` in [e-entity/freme-ner/documents](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/executeFremeNer) and all predefined default parameters, the output is the following:

``` 
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .

<http://freme-project.eu/#char=0,42>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "42"^^xsd:int ;
        nif:isString    "Welcome to Berlin, the capital of Germany."^^xsd:string .
```

although the output without setting the **types** parameter contains : 
```
<http://freme-project.eu/#char=11,17>
        a                     nif:RFC5147String , nif:Phrase , nif:Word , nif:String ;
        nif:anchorOf          "Berlin"^^xsd:string ;
        nif:beginIndex        "11"^^xsd:int ;
        nif:endIndex          "17"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,42> ;
        itsrdf:taClassRef     <http://dbpedia.org/ontology/Location> , <http://dbpedia.org/ontology/Region> , <http://dbpedia.org/ontology/PopulatedPlace> , <http://dbpedia.org/ontology/Place> , <http://dbpedia.org/ontology/AdministrativeRegion> , <http://nerd.eurecom.fr/ontology#Location> ;
        itsrdf:taConfidence   "0.6754807097330983"^^xsd:double ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Berlin> .
```

**Comment by m1ci** [comment]
here is what I get when processing the same text with types=http%3A%2F%2Fdbpedia.org%2Fontology%2FLocation

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Welcome%20to%20Berlin,%20the%20capital%20of%20Germany.&outformat=turtle&language=en&dataset=dbpedia&types=http%3A%2F%2Fdbpedia.org%2Fontology%2FLocation

The results are as expected, only Location entities are returned.

**Comment by bgrusdt** [comment]
@ArneBinder  can you try this as well? I keep getting a different result. Thanks for your reply.

**Comment by m1ci** [comment]
please share your cURL

**Comment by bgrusdt** [comment]
yes, sure: 
```
curl -X POST --header 'Content-Type: text/plain' --header 'Accept: text/turtle' 'http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Welcome%20to%20Berlin%2C%20the%20capital%20of%20Germany.&language=en&dataset=dbpedia&mode=all&types=http%253A%252F%252Fdbpedia.org%252Fontology%252FLocation'
```

**Comment by m1ci** [comment]
the URI http%253A%252F%252Fdbpedia.org%252Fontology%252FLocation is incorrectly encoded, the correct one is http%3A%2F%2Fdbpedia.org%2Fontology%2FLocation

This should fix your problem

**Comment by bgrusdt** [comment]
That does work when I use the correctly encoded url in the curl command. But there seems to be a problem on the documentation page then, because I did actually copy the correctly encoded url to the types parameter field, but the generated curl contains the  wrong url: 
```
types=http%253A%252F%252Fdbpedia.org%252Fontology%252FLocation
```

**Comment by ArneBinder** [comment]
The documentation encodes the parameter already. So just put `http://dbpedia.org/ontology/Location` in the input field.

**Comment by bgrusdt** [comment]
Okay, this finally works then. Thanks. So we should update the description of the types parameter.

**Comment by ArneBinder** [comment]
Can we close this?

**Comment by bgrusdt** [comment]
I think that's clear now and we can close it. Thank you.
