### ISSUE TITLE
[dataset upload] properties parameter

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-ner#120]
At the moment, the `properties` parameter is discarded, but mentioned at [POST a new dataset](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/createDataset), but not in [update a dataset](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/updateDataset). 
[This line](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerManageDatasets.java#L131-L132) indicates that `fremeNer.addToDataset` is called with just an empty list.
@m1ci @sandroacoelho implements FremeNer the related functionality? What should we do here?

**Comment by m1ci** [comment]
The properties parameter has been implemented and used before the migration to the new arch.
Nevertheless, the properties parameter is optional and if it is not used the FREME NER will index every dc:label, skos:prefLabel and skos:altLabel literals.
Using the properties parameter, the client can specify the additional properties that should be indexed, e.g. foaf:name
Dont recall if this was implemented for the PUT, but indeed it should be there as well.

@sandroacoelho can you please make sure the properties parameter is correctly used in POST and PUT?

**Comment by jnehring** [comment]
I think that @bgrusdt can perform this task also.

**Comment by m1ci** [comment]
ok, let @bgrusdt do that. thanks.

**Comment by bgrusdt** [comment]
I couldnt test it since the creation of datasets failed. When this is solved, I will do it.
Wait for #136 .

**Comment by bgrusdt** [comment]
The properties parameter was implemented in the scala code, but as @ArneBinder mentioned, it was never used. I included it and tested it  for PUT and POST which both worked. 
But when it is set, it does not index the additional properties but **only** the properties defined in the properties parameter and not the default ones, dc:label, skos:prefLabel and skos:altLabel literals. 
[Here](https://github.com/freme-project/freme-ner/blob/master/src/main/scala/org/elinker/core/api/scala/FremeNer.scala#L110-L118) is the relevant scala code. 

Shall I change this such that the default ones are always included?

**Comment by jnehring** [comment]
To me the suggested change makes sense but lets wait what @m1ci says.

**Comment by m1ci** [comment]
> @m1ci Shall I change this such that the default ones are always included?

I would suggest following:
- the properties parameter is optional
- if it is not set then dc:label, skos:prefLabel and skos:altLabel are considered
- if it is set, then only the specified properties are considered and not the dc:label, skos:prefLabel and skos:altLabel

**Comment by jnehring** [comment]
Ok. Then lets do it this way. I think in this case the work is done?

@bgrusdt can you please check if it is properly documented which properties are considered for indexing? When the documentation is correct then I think we can close this issue.

**Comment by bgrusdt** [comment]
I added a short note about the behavior wrt the default  values, [see here (Note 1)](http://freme-project.github.io/api-doc/full.html#!/e-Entity/createDataset). The rest was properly documented.
