### ISSUE TITLE
FREME NER life version may be down

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-ner#121]
See attached CURL requests. The one going to FREME dev works, the other not. This was reported from Martin Wunderlich, see
https://twitter.com/martin_wun/status/755711296922853376

[curl-requests-live-versus-dev-version.txt](https://github.com/freme-project/freme-ner/files/373443/curl-requests-live-versus-dev-version.txt)

**Comment by sandroacoelho** [comment]
@fsasaki , @jnehring: the service is up again

**Comment by jnehring** [comment]
@sandroacoelho what happened?

**Comment by sandroacoelho** [comment]
I just connect in the server and checked using ps that the service was not available, then I restart it. I will check our logs and tell you the root cause.

**Comment by jnehring** [comment]
Thank you. I stopped FREME NER on freme-live on monday, uploaded the new version and started it as part of the 0.8 release. 10 minutes after the start I got an exception: java.lang.OutOfMemoryError: Java heap space. Then I just restarted FREME NER and this time it worked. Maybe its again the out of memory error.

**Comment by fsasaki** [comment]
There still seem to be some issues, see from
https://twitter.com/martin_wun/status/755735015938482176

> the 502 is gone and has changed to a 400

**Comment by fsasaki** [comment]
I checked

http://api.freme-project.eu/doc/current/freme-showcase/xml-to-rdf.html

and it is borken too. It uses the life version of FREME NER. Nothing has chanced in the demo javascript code recently.

**Comment by jnehring** [comment]
FREME NER itself is running. http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=de&dataset=dbpedia&informat=text&input=Welcome%20to%20Berlin%2C%20the%20capital%20of%20Germany! returns data coming from FREME NER. I will further investigate this.

**Comment by jnehring** [comment]
The problem happened both on freme-live and freme-dev. Somehow FREME NER was started in a strange way for both servers. I stopped both packages and restarted them. Now http://api.freme-project.eu/doc/current/freme-showcase/xml-to-rdf.html seems to work.

@fsasaki can you please verify that it works now?

**Comment by fsasaki** [comment]
works, thanks!
