### ISSUE TITLE
Use another library for entity spotting

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#122]
I received this email today:

Hi Jan, Milan

Gary has been investigating methods to possibly increase the quality of the spotting. 

Google has a library for example although it doesn't actually do the entity spotting. It just labels parts of speech in the text. That's still a major component in the accuracy of spotting though.

Can we maybe use this as improvement in the quality of entities in the case this tool is used as the first step in the spotting process.

https://research.googleblog.com/2016/05/announcing-syntaxnet-worlds-most.html

https://spacy.io/blog/syntaxnet-in-context

Is this of any interest? Not saying it needs to be implemented by FREME however we (ADAPT and Wripl) are very keen on understanding and enhancing the quality of the spotting.  

regards
Kevin

**Comment by jnehring** [comment]
You can do entity spotting with another library. The easiest way to do this is to do this on the client side. Then you can use FREME NER for linking only using the mode parameter. In this way you use the google tool for entity spotting and FREME NER for entity linking.

**Comment by sandroacoelho** [comment]
It would be awesome if FREME-NER turns a kind of HUB of spotting service.

**Comment by fsasaki** [comment]
> It would be awesome if FREME-NER turns a kind of HUB for spotting services.

+1 :)
