### ISSUE TITLE
Make data in triple store available

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#126]
The FREME triple store stores some datasets that we need to make available. I think the process is

1. We identify all data that is in the triple store
2. We see which data needs to be made available
3. We make the data available as downloads and documentation

About 1: I think in the triple store there are these datasets:

* Parts of the dbpedia for the domains feature of FREME NER. This needs to be available. I think we also need to make some documentation available how to update this data when a new version of DBPedia is available.
* Parts of DBPedia to allow fetching of labels to entities. We need to make this available at least to ADAPT research centre.

@m1ci do you know of any other datasets stored in our triple store?

**Comment by m1ci** [comment]
in triple store are stored types and labels info for the entities.
The types triples are stored in the http://www.freme-project.eu/datasets/types graph and there is type info for entities from:
- DBpedia
- CORDIS
- Geopolitical ontology
- Global airports
- ONLD
- ORCID

**Comment by jnehring** [comment]
dublicate of https://github.com/freme-project/freme-docker/issues/17
