### ISSUE TITLE
Make freme ner models public / license

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#127]
We made the models that we trained for FREME NER publicly available [here](http://api.freme-project.eu/datasets/ner-trained-models/wikiner/). I think we should add a link to the folder to the [freme-ner documentation](http://api.freme-project.eu/doc/current/knowledge-base/freme-for-api-users/freme-ner.html) and also add a license for the models.

I suggest we make all models we trained available under Apache 2.0 license, like the rest of FREME. Is this ok with you, @m1ci, @kurzum ?

**Comment by m1ci** [comment]
Since the models were trained on CC-BY data (Wikipedia/DBpedia) I would share these models under the same license, CC-BY.

**Comment by jnehring** [comment]
I assume CC-BY in the latest version 3.0? The link you provided is not clear about that.

**Comment by reckart** [comment]
The latest version of the CC licenses is 4.0.

DBPedia says CC-BY-SA 3.0 (http://wiki.dbpedia.org/about)
Wikipedia also says CC-BY-SA 3.0 (https://en.wikipedia.org/wiki/Wikipedia:Copyrights)

**Comment by reckart** [comment]
Actually Wikipedia says "Creative Commons Attribution-Share-Alike License 3.0 or later." at https://en.wikipedia.org/wiki/Wikipedia:Copyrights

**Comment by m1ci** [comment]
> I assume CC-BY in the latest version 3.0? The link you provided is not clear about that.

Yes, 3.0, same as DBpedia/Wikipedia.

**Comment by nilesh-c** [comment]
@m1ci are these actually DBpedia abstracts models? AFAIR I trained these models using data from http://schwa.org/projects/resources/wiki/Wikiner (which is also CC-BY 3.0, but I guess some attribution would be nice)

**Comment by m1ci** [comment]
abstracts

**Comment by m1ci** [comment]
@jnehring can we close the issue?

**Comment by jnehring** [comment]
@bgrusdt 

* please add a note to the [documentation of freme-ner](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#how-to-install) next to the section "Trained NER model files for the languages you want to support". It should say that the data is licensed under Creative Commons Attribution-ShareAlike 3.0 license and the link to https://creativecommons.org/licenses/by-sa/3.0/ . Further it should add a sentence that the models where created using the dbpedia abstracts corpus because the license obliges us to state that. link to http://wiki-link.nlp2rdf.org/abstracts/ 
* Then add a file LICENSE next the location of the datasets with the same note. The datasets are located on freme-live somewhere in /var/www/html folder.

**Comment by bgrusdt** [comment]
@jnehring 
I added two sentences about the license and creation of the models to the [documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#how-to-install)
and added a LICENSE.txt file with the same information to this folder on freme-live:
var/www/html/datasets/ner-trained-models/wikiner.  
So can this be closed?

**Comment by jnehring** [comment]
Thank you, this issue is solved.
