### ISSUE TITLE
Upload datasets to the server

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#130]
Please upload all datasets from the [list of datasets](http://api-dev.freme-project.eu/doc/api-doc/list-datasets.html) to freme-live server. You can find the datasets (and some more) [here](https://www.dropbox.com/sh/c4otelnrga249g6/AAAwepRh3ObZz4lWk2tTVJJca?dl=0). We need only the datasets from the list of datasets. Please store the datasets in the folder `/var/www/html/datasets/freme-ner-datasets`

**Comment by jnehring** [comment]
Please upload only

* loc-authors
* europeana 

The other datasets should be transfered using SSH to the FREME server by someone who has access to  the AKSW server that hosts the data.

**Comment by m1ci** [comment]
AKSW does not host these datasets. loc-authors is available through the library of congress download page, the europeana was provided by @pheyvaer

**Comment by jnehring** [comment]
I created https://github.com/freme-project/dataset-conversion-scripts/issues/4 to add the scripts for eureopana
