### ISSUE TITLE
FREME NER live stops

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#131]
freme ner live stopped yesterday at 11am. There was no hint in the log files what has happened. The same  happened on 26th of july.

@sandroacoelho do you have an idea what can go wrong? I think this failures occur since the FREME 0.8 update last week monday.

**Comment by sandroacoelho** [comment]
checking the problem

**Comment by jnehring** [comment]
I think it was stopped manually so we can close this issue
