### ISSUE TITLE
change behaviour of numLinks parameter

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#133]
Currently, the value of the `numLinks` parameter refers to the total number of links returned for the entity.
We need to change this behaviour so that the `numLinks` parameter refers to the number of links returned for the entity for each dataset.

For example, if there is the entity `Berlin`, the `numLinks` is set to `1` (default value), and the user specifies for datasets `dbpedia` and `wriplcustom` as datasets, then it should return two links, one for `dbpedia` and one for the `wriplcustom` dataset.

Try:
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Berlin%20is%20in%20Germany.&outformat=turtle&language=en&dataset=dbpedia,wriplcustom&numLinks=1

It returns only one link for Berlin but it should return two links (there is link in `DBpedia` and also in `wriplcustom`).

@sandroacoelho can you please change the behaviour of the numLinks param?

adding @koidl, @jnehring and @xFran into the loop.

**Comment by sandroacoelho** [comment]
Hi @m1ci  ,

I created a test case for this and the behaviour requested is already implemented.  It is strange that the instance under http://api-dev.freme-project.eu/ is producing a distinct result. 
Is this instance using the latest master branch codebase?




Result:
```
@prefix` xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .

<http://freme-project.eu#char=0,21>
        a               nif:RFC5147String , nif:Context , nif:String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "21"^^xsd:int ;
        nif:isString    "Berlin is in Germany."^^xsd:string .

<http://freme-project.eu#char=13,20>
        a                     nif:Word , nif:RFC5147String , nif:Phrase , nif:String ;
        nif:anchorOf          "Germany"^^xsd:string ;
        nif:beginIndex        "13"^^xsd:int ;
        nif:endIndex          "20"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu#char=0,21> ;
        itsrdf:taConfidence   "0.9999999441738809"^^xsd:double ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Germany> .

<http://freme-project.eu#char=0,6>
        a                     nif:RFC5147String , nif:String , nif:Word , nif:Phrase ;
        nif:anchorOf          "Berlin"^^xsd:string ;
        nif:beginIndex        "0"^^xsd:int ;
        nif:endIndex          "6"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu#char=0,21> ;
        itsrdf:taConfidence   "0.9998456811833493"^^xsd:double ;
        itsrdf:taIdentRef     <http://www.freme-projects.eu/dataset/people/Berlin> , <http://dbpedia.org/resource/Berlin> .
```

**Comment by jnehring** [comment]
It did not get redeployed automatically because the version of freme-ner was still set to 0.7, while you implemented your changes in 0.8-SNAPSHOT in [freme-parent](https://github.com/freme-project/freme-parent/edit/master/pom.xml). I changed this but still it seems not to work. 

I checked the configuration and I am pretty sure that freme-worker runs the latest version of FREME NER now but it still produces only one link. Can you somehow make sure that the latest version does not get deployed? Maybe adding a debug message in the log file and checking the logfile for this message. Then we can make sure that it does not run the latest version and I can further trace the problem.

**Comment by sandroacoelho** [comment]
Hi @jnehring , Could you please try again? 

I was indexing our new solrdev. I went back to the old instance. 

I will continue this operation in the early hours in Germany.

Best,

**Comment by jnehring** [comment]
I tested it and it works now. So can we close this issue?

**Comment by m1ci** [comment]
just checked, and I can also confirm that it works.
