### ISSUE TITLE
Reindex  freme-dev and freme-live with existing datasets

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#134]
#91

**Comment by jnehring** [comment]
Please tell the partners in advance when you plan to do it on freme-live because I guess it will make FREME live unavailable for some time.

**Comment by sandroacoelho** [comment]
I am planning to perform our reindex as follow

<table>
  <tr>
     <td><b>Instance</b></td>
     <td><b>Reindex time</b></td>
  </tr>
  <tr>
     <td>solr-dev</td>
     <td>Monday 22:00 to 06:00</td>
  </tr>
  <tr>
     <td>solr-dev</td>
     <td>Tuesday 22:00 to 06:00</td>
  </tr>
</table>


<table>
  <tr>
     <td><b>Instance</b></td>
     <td><b>Reindex time</b></td>
  </tr>
  <tr>
     <td>solr-dev</td>
     <td>Tuesday 22:00 to 06:00</td>
  </tr>
  <tr>
     <td>solr-dev</td>
     <td>Wednesday 22:00 to 06:00</td>
  </tr>
</table>


Who should I ask if I can go ahead?

Best,

**Comment by jnehring** [comment]
The table says solr-dev only, what about solr live?

Lets announce these downtimes on next developers call.

**Comment by sandroacoelho** [comment]
ops... for Solr Live is

<table>
  <tr>
     <td><b>Instance</b></td>
     <td><b>Reindex time</b></td>
  </tr>
  <tr>
     <td>solr-live</td>
     <td>Tuesday 22:00 to 06:00</td>
  </tr>
  <tr>
     <td>solr-live</td>
     <td>Wednesday 22:00 to 06:00</td>
  </tr>
</table>

**Comment by m1ci** [comment]
is this task done?

**Comment by sandroacoelho** [comment]
Hi @m1ci . Yes. We can close it.
