### ISSUE TITLE
P3: Include confidence scores

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#14]
Include confidence scores to the output.
Confidence will be encoded as `itsrdf:taConfidence`

**Comment by m1ci** [comment]
Thanks for reporting this bug. The confidence scores have been fixed. They represents the level of confidence a surface form being correctly recognized as a named entity.

**Comment by m1ci** [comment]
please check and close.

**Comment by jnehring** [comment]
It works fine. Nice work!
