### ISSUE TITLE
Solr: when a dataset is deleted, all documents should be removed

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#145]

**Comment by jnehring** [comment]
This sounds important to me.

**Comment by m1ci** [comment]
This lines of code should do that
https://github.com/freme-project/freme-ner/blob/master/src/main/scala/org/elinker/core/api/process/Datasets.scala#L102-L104

**Comment by jnehring** [comment]
related to https://github.com/freme-project/FREMECommon/issues/37
