### ISSUE TITLE
Badges (code test coverage and travis-ci)

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#147]
Hi @jnehring ,

I would like to put some badges in readme for FREME-NER, such as coveralls - code test coverage and it works together with Travis-CI.  

Do you know if  we are some restriction or if we are authorized to enable Travis? If is permited and there is not issue related, who could enable Travis-CI for us ( https://travis-ci.org/freme-project/freme-ner ?)  

Best,

**Comment by jnehring** [comment]
Hey, we are already using travis-ci for the documentation homepage. But lets discuss this on todays developers call because it is not clear to me right now what travis does and why we need it.

**Comment by sandroacoelho** [comment]
:+1:  

Just to know, see this repo https://github.com/AKSW/RDFUnit. It has some badges that I would like to put in FREME-NER

**Comment by jnehring** [comment]
I changed your permissions. Now InfAI team has admin access to freme-ner repository. So you can configure travis as you like.

**Comment by sandroacoelho** [comment]
It works. Great thanks @jnehring

**Comment by jnehring** [comment]
I see the "build passing" badge in the freme-ner. Can you please explain what this means? What does travis-ci do?

**Comment by sandroacoelho** [comment]
Hi @jnehring , sure! 

Travis-CI do the same work that Jenkins just with an yml file. If the build runs without errors, you will see "Build passing" otherwise  "Build failing" is shown.

The main advantage is that you can use a lot of cloud services  that runs together with travis and let it public through Badges in your README.md.

Some services available online that can be integrate with Travis (or not):
- coveralls.io - Automated test coverage checker
- codacy.com - Want's to save time with in the code review process? 
- codebeat.co - Analyze your code with a public "sonar"

**Comment by jnehring** [comment]
ok thanks
