### ISSUE TITLE
fails with informat=text/html caused by different nif prefix

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-ner#151]
This request

```
curl -X POST -H "Content-Type: text/plain" -H "Accept: text/turtle" -H "Cache-Control: no-cache" -H "Postman-Token: ee4bc3dd-e67c-b3a7-0357-4803b82280d2" -d '<p>The Eiffel Tower (/ˈaɪfəl ˈtaʊər/ EYE-fəl TOWR; French: tour Eiffel [tuʁ‿ɛfɛl] About this sound listen) is a wrought iron lattice tower on the Champ de Mars in Paris.</p>' "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&informat=html"
```

produces a `BadRequestException.` 

It happens because the input html is converted to turtle, but with nif version 2.0. The extractFirstPlaintext used in the FRemeNerEnrichment tries to iterate only over `context` resources with the nif prefix `http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#`.

**Comment by jnehring** [comment]
caused by https://github.com/freme-project/basic-services/issues/106

**Comment by ArneBinder** [comment]
Should be fixed, @jnehring please review.

**Comment by jnehring** [comment]
i need to re-activate jenkins in order to see if this is fixed. will do it tomorrow

**Comment by ArneBinder** [comment]
Jenkins is re-activted and now this works on dev.

**Comment by jnehring** [comment]
This works now.
