### ISSUE TITLE
Research dataset update cycles

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#152]
From [making FREME assets available](https://docs.google.com/document/d/1qlA2LyqKwGeO_ds9hFNDzKT_Wd_C7wv6z4CIK_PLiSo/edit#)

Research dataset update cycles and add to documentation.

**Comment by m1ci** [comment]
done, see the "update frequency" column of the "List of FREME datasets" table.

**Comment by jnehring** [comment]
thank you
