### ISSUE TITLE
FREME NER does not compile

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#158]
See http://rv1443.1blu.de:8082/job/freme-ner/373/console

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

I've needed to update the NIF library and keep the version. Could you please use -U (mvn clean install -U) option in maven or remove NIF from the maven lib cache(rm -r .m2/repository/org/nlp2rdf/nif/)?

Thanks

**Comment by jnehring** [comment]
I removed the lib from the maven cache and rebuild the project. Now it works. Thank you!
