### ISSUE TITLE
Update dataset fails on live

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-ner#159]
Updating a dataset from the [full API](https://freme-project.github.io/api-doc/full.html#/) fails with response code 0 and response headers:
```
{
  "error": "no response from server"
}
```
The response body contains: " no content"

When I use Postman to do the request, I get this error:

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/e-entity/freme-ner/datasets/testSetbrgru/",
  "message": "Error from server at http://rv2622.1blu.de/solrlive: /opt/solr/server/solr/elinker/data/index/_9fv2_Lucene50_0.pos",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1476106893438
}
```

It does work on the dev version.  

This seems to be related or the same as  this issue #157 .

**Comment by sandroacoelho** [comment]
Hi @bgrusdt 

Could you please try again? Seems that our FREME-LIVE index was corrupted. I fixed it using our backup.

**Comment by bgrusdt** [comment]
Thank you @sandroacoelho , it works now!
