### ISSUE TITLE
nif:taMsClassRef

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#160]
@m1ci , @koidl have requested to fill the property nif:taMsClassRef with the most specific one based on the dbpedia ontology.

E.g:
```
<http://freme-project.eu/#offset_0_14>
        a                     nif:OffsetBasedString , nif:Phrase ;
        nif:anchorOf          "Diego Maradona"^^xsd:string ;
        nif:annotationUnit    [ a                       nif:EntityOccurrence ;
                                itsrdf:taAnnotatorsRef  <http://freme-project.eu/tools/freme-ner> ;
                                itsrdf:taClassRef       <http://nerd.eurecom.fr/ontology#Person> , <http://dbpedia.org/ontology/SoccerManager> , <http://dbpedia.org/ontology/Agent> , <http://dbpedia.org/ontology/SportsManager> , <http://dbpedia.org/ontology/Person> ;
                                nif:taMsClassRef <http://dbpedia.org/ontology/SoccerManager> ;
                                itsrdf:taConfidence     "0.9869992701528016"^^xsd:double ;
                                itsrdf:taIdentRef       <http://dbpedia.org/resource/Diego_Maradona>
                              ] ;
        nif:beginIndex        "0"^^xsd:nonNegativeInteger ;
        nif:endIndex          "14"^^xsd:nonNegativeInteger ;
        nif:referenceContext  <http://freme-project.eu/#offset_0_33> .

```

**Comment by sandroacoelho** [comment]
Basically, it can be retrieved the following [SPARQL Query](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+%3Ftype+WHERE+%7B+%0D%0A%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Ftype+.+%0D%0AFILTER+NOT+EXISTS+%7B+%0D%0A++++%3Fsubtype+%5Ea+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3B%0D%0A+++++++++++++rdfs%3AsubClassOf+%3Ftype+.%0D%0A++%7D%0D%0AFILTER+regex%28str%28%3Ftype%29%2C+%22dbpedia.org%2Fontology%2F%22%29%0D%0A%7D%0D%0A%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)

```
SELECT ?type WHERE { 
<http://dbpedia.org/resource/Diego_Maradona> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type . 
FILTER NOT EXISTS { 
    ?subtype ^a <http://dbpedia.org/resource/Diego_Maradona> ;
             rdfs:subClassOf ?type .
  }
FILTER regex(str(?type), "dbpedia.org/ontology/")
}

```

**Comment by sandroacoelho** [comment]
Hi @m1ci : I ran the same query at [http://rv2622.1blu.de:8890/sparql](http://rv2622.1blu.de:8890/sparql?default-graph-uri=&query=SELECT+%3Ftype+WHERE+%7B+%0D%0A%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Ftype+.+%0D%0AFILTER+NOT+EXISTS+%7B+%0D%0A++++%3Fsubtype+%5Ea+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3B%0D%0A+++++++++++++rdfs%3AsubClassOf+%3Ftype+.%0D%0A++%7D%0D%0AFILTER+regex%28str%28%3Ftype%29%2C+%22dbpedia.org%2Fontology%2F%22%29%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on) and did not get the same result as DBpedia SPARQL. I would bet that this problem is related to our indexed data. Just to ensure that I am in the right way, could you please check if my SPARQL is correct? 

Thank you

**Comment by m1ci** [comment]
Hi @sandroacoelho 
the query at the FREME sparql endpoint did not work because the dbpedia ontology wasn't loaded and there were the required subClassOf statements. Now it shoud work.
Try [http://rv2622.1blu.de:8890/sparql](http://rv2622.1blu.de:8890/sparql?default-graph-uri=&query=SELECT+%3Ftype+WHERE+%7B+%0D%0A%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E+%3Ftype+.+%0D%0AFILTER+NOT+EXISTS+%7B+%0D%0A++++%3Fsubtype+%5Ea+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FDiego_Maradona%3E+%3B%0D%0A+++++++++++++rdfs%3AsubClassOf+%3Ftype+.%0D%0A++%7D%0D%0AFILTER+regex%28str%28%3Ftype%29%2C+%22dbpedia.org%2Fontology%2F%22%29%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)

@sandroacoelho can you now implement so that we have the nif:taMsClassRef property in the NIF output?
thanks!

**Comment by sandroacoelho** [comment]
Hi @m1ci. As I promised,  nif:taMsClassRef is already implemented. Could you please test it?

Best

**Comment by m1ci** [comment]
I dont see the nif:taMsClassRef in the output, see
https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&outformat=turtle&informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&nif-version=2.1

**Comment by sandroacoelho** [comment]
Hi @m1ci ,

Checking Jenkins, I saw that the main jar is not using SNAPSHOTS. The build is using our last stable version 0.11 that does not contain this new feature.

I [forced it](https://github.com/freme-project/freme-packages/commit/7859f34d34c48f3eb6237b5a262b47155d11c621) to give you a chance to test  - (Note: This is wrong and should be reversed as soon as possible) .

At [SPARQLProcessor.java](https://github.com/freme-project/freme-ner/blob/002c7c742b0609fc4c886ac2cbdd53b98f10fdbb/src/main/java/org/elinker/core/api/java/utils/SPARQLProcessor.java#L48), the address "http://www.freme-project.eu/datasets/types" is used as defaultGraph. Could you please load the DBpedia ontology inside it? 

Best,

**Comment by m1ci** [comment]
> At SPARQLProcessor.java, the address "http://www.freme-project.eu/datasets/types" is used as defaultGraph. Could you please load the DBpedia ontology inside it?

Can you try without specifying the default graph?
Just
`QueryExecution qexec = QueryExecutionFactory.sparqlService(this.endpoint, query);

**Comment by sandroacoelho** [comment]
Hi @m1ci , Done!

**Comment by m1ci** [comment]
Thanks, however for https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&outformat=turtle&informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&nif-version=2.1
I get one type for Diego Maradna, which is fine, but two types for Argentina - problem. Why there are two types for Argentina?

**Comment by m1ci** [comment]
I found the reason why,
actually, in the dbpedia ontology there is
`<http://dbpedia.org/ontology/Place> <http://www.w3.org/2002/07/owl#equivalentClass> <http://dbpedia.org/ontology/Location> .`

which means they are same types. In order to return only one, just add LIMIT 1 at the end of the query. That will solve the isssue.

**Comment by m1ci** [comment]
I found why, there is no subclass relation between http://dbpedia.org/ontology/Country and http://dbpedia.org/ontology/Location, also Location is sameAs Place. We need to fix the sparql query.

**Comment by sandroacoelho** [comment]
By definition, our query retrieves leafs (a type that does not have subtypes) for the most specific types in DBpedia ontology. 

For Argentina, we have [two "leafs" types](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+%3Ftype+WHERE+%7B+%0D%0A<http%3A%2F%2Fdbpedia.org%2Fresource%2FArgentina>+<http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type>+%3Ftype+.+%0D%0AFILTER+NOT+EXISTS+%7B+%0D%0A++++%3Fsubtype+%5Ea+<http%3A%2F%2Fdbpedia.org%2Fresource%2FArgentina>+%3B%0D%0A+++++++++++++rdfs%3AsubClassOf+%3Ftype+.%0D%0A++%7D%0D%0AFILTER+regex%28str%28%3Ftype%29%2C+"dbpedia.org%2Fontology%2F"%29%0D%0A%7D%0D%0A&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)  and it could happen with others.

If we want just one resource  to fill in nif:taMsClassRef, we could

1) Takes the first (I don't like this solution because is not deterministic);

2) Define filters to decide what type we should select to be a nif:taMsClassRef

Best,

**Comment by m1ci** [comment]
not, it's one leaf and its Country. Location is super class.

**Comment by m1ci** [comment]
Here is the solution
```
SELECT ?type WHERE { 
<http://dbpedia.org/resource/Argentina> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type . 
FILTER NOT EXISTS { 
    <http://dbpedia.org/resource/Argentina> a ?subtype .
    ?subtype rdfs:subClassOf|owl:equivalentClass ?type .
  }
FILTER regex(str(?type), "dbpedia.org/ontology/")
}
```

@sandroacoelho please update the query

**Comment by sandroacoelho** [comment]
@m1ci : done!

**Comment by m1ci** [comment]
thanks @sandroacoelho 

@koidl @xFran please test, for example: https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&outformat=turtle&informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&nif-version=2.1

**Comment by jnehring** [comment]
> the query at the FREME sparql endpoint did not work because the dbpedia ontology wasn't loaded and there were the required subClassOf statements. Now it shoud work.

Do we need to update the dataset dumps for the docker installation because of that?

**Comment by jnehring** [comment]
Oh forget the last comment, I just read https://github.com/freme-project/freme-docker/issues/17#issuecomment-258323248 which says we need to update the dataset

**Comment by m1ci** [comment]
@sandroacoelho do we need to update the dataset? I think it is irrelevant in which graph are the datasets loaded, we query all data in all graphs. Correct me if Im wrong.

**Comment by xFran** [comment]
@m1ci is working with turtle but no json-ld

https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&outformat=json-ld&informat=text&input=Diego Maradona is from Argentina.

I can't see nif:taMsClassRef  or something similar in the response.

**Comment by sandroacoelho** [comment]
Hi, @xFran: I will check our jsonld.

**Comment by fsasaki** [comment]
It works with NIF version 2.1, see http://tinyurl.com/jedem72

2016-11-14 13:32 GMT+01:00 Sandro <notifications@github.com>:

**Comment by xFran** [comment]
Works with  NIF version 2.1 indeed.

https://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all&outformat=json-ld&informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&nif-version=2.1

Thank you @fsasaki

**Comment by jnehring** [comment]
I have a few questions about this feature:

* Would it be complicated to add a configuration option to switch off the feature? I guess it has a huge impact on the performance of NER.
* What happens when the data for this feature is not contained in the triple store? Does it produce no MFS value? Or an error message?
* Is there any documentation about the feature? We should add a (brief) documentation to https://freme-project.github.io/knowledge-base/freme-for-api-users/freme-ner.html

**Comment by m1ci** [comment]
> Would it be complicated to add a configuration option to switch off the feature? I guess it has a huge impact on the performance of NER.

I would not complicate the things. And provide this info always. In other words, leave as it is.

> What happens when the data for this feature is not contained in the triple store? Does it produce no MFS value? Or an error message?

If there is no data, then we dont provide the mfs value. If there is then we provide. Also, if there is just one type, then we list this type as most-specific-type and also as itsrdf:taClassRef.

> Is there any documentation about the feature? We should add a (brief) documentation to https://freme-project.github.io/knowledge-base/freme-for-api-users/freme-ner.html

I'm afraid this is not documented. Please add section to the doc called "NIF Output explained" and explain each piece of information (1-2 sentences).

**Comment by jnehring** [comment]
| Would it be complicated to add a configuration option to switch off the feature? I guess it has a huge impact on the performance of NER.

| I would not complicate the things. And provide this info always. In other words, leave as it is.

Ok

thanks for the information

**Comment by jnehring** [comment]
I tested and this is installed on freme-live also. The documentation issue is moved to https://github.com/freme-project/freme-project.github.io/issues/320 . So this issue is done
