### ISSUE TITLE
cannot upload new dataset

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-ner#162]
See attached request. To run the request, you need to fill in your token.

The new dataset always has 0 entities. 
[request.txt](https://github.com/freme-project/freme-ner/files/589164/request.txt)

**Comment by sandroacoelho** [comment]
Hi @fsasaki , @jnehring 

This error was fixed. 

We need to deploy it to test, but  our Jenkins task to it is disabled. 

Best,

**Comment by fsasaki** [comment]
> We need to deploy it to test, but our Jenkins task to it is disabled.

thanks; does this mean that the fix is not yet deployed on FREME dev or live?

**Comment by m1ci** [comment]
@sandroacoelho jenkins is re-enabled. @sandroacoelho Can you check if this is fixed? Maybe you'll need to force build of freme ner in jenkins.

**Comment by sandroacoelho** [comment]
Hi @m1ci, thanks :+1: I'ves tested in dev and it works

@fsasaki : Could you please test in freme-dev again? 

Best,

**Comment by jnehring** [comment]
@fsasaki said in an email that it works now for him. I need to update the live version before the SWIB tutorial.

**Comment by jnehring** [comment]
This is fixed on freme-live through the release
