### ISSUE TITLE
FREME NER understands English only

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#172]
I think FREME NER has loaded the English language model only. Please do this:

1) Download all language models from here: http://api.freme-project.eu/datasets/ner-trained-models/wikiner/ . Copy the models to /home/francisc/freme-install/freme-ner-models
(there is no model for German in the download. The German model is stored somewhere else and is always available)

2) Change the application.properties file:

freme.ner.languages=en,de,nl,fr,it,es,ru

3) Restart FREME

**Comment by munnellg** [comment]
@jnehring This should be resolved now

**Comment by jnehring** [comment]
i tested this and it works. great!
