### ISSUE TITLE
FREME NER does not start

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#174]
Error message in /opt/freme-ner-dev/logs/broker.log on rv2622.1blu.de

```
ERROR   2017-01-23 17:05:07,221 [main] org.springframework.boot.SpringApplication  - Application startup failed
eu.freme.common.exception.InternalServerErrorException: It was not possible to read the spotter dictionary. Please check if the path is correct (/opt/freme-ner-dev/dictionary)
        at org.elinker.core.spotter.FremeSpotter.buildDictionary(FremeSpotter.java:42)
        at org.elinker.core.spotter.FremeSpotter.onApplicationEvent(FremeSpotter.java:65)
        at org.elinker.core.spotter.FremeSpotter.onApplicationEvent(FremeSpotter.java:21)
```

Can you please

1) Add a fall back behaviour that it can start even when it is not configured correctly
2) Put the resource somewhere else. The folder /opt/freme-ner-dev gets deleted whenever Jenkins reinstalls freme-ner. A good place is this folder](https://github.com/freme-project/freme-packages/tree/master/freme-ner-dev/src/main/resources), if it not too large. This gets deployed to /opt/freme-ner-dev/config .

**Comment by sandroacoelho** [comment]
Fixed. Thanks @jnehring .
