### ISSUE TITLE
Datasets were deleted

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#175]
On freme-dev most datasets were deleted: http://rv1443.1blu.de/current/e-entity/freme-ner/datasets/

@sandroacoelho do you know what happened? Can you assure that this will not happen when we install it on live? And that this will not happen before / during the review?

Also the API call to retrieve e-Link templates does not work anymore: http://rv1443.1blu.de/current/e-link/templates

**Comment by munnellg** [comment]
@jnehring That's done now

**Comment by sandroacoelho** [comment]
Hi @jnehring,

During our tests with Gustavo, we had to recreate our mysql schema because it is not working well.
I have a backup and will restore the data asap.

Thanks

**Comment by jnehring** [comment]
Please restore the data because we found out that some important data was stored in the dev server which we need to migrate to live: https://github.com/freme-project/basic-services/issues/121

**Comment by jnehring** [comment]
I restored the database from a backup from 2016-12-14. @sandroacoelho I guess that now at least the last datasets you added to the system in #171  are removed. I have a backup in case you want to restore data.

**Comment by sandroacoelho** [comment]
Thank you a lot!
