### ISSUE TITLE
implement mode parameter

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#23]
Implement `mode` parameter which will enable to do just `spotting` or `spotting+linking`
E.g., `mode=spotting,linking`

**Comment by m1ci** [comment]
the `mode` param has been also implemented in e-Entity. Please check and close.
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Diego+Maradona+is+from+Argentina.&outformat=turtle&language=de&dataset=dbpedia&mode=spot,link

**Comment by jnehring** [comment]
I tested it and it works fine. Please provide doumentation: https://github.com/freme-project/Documentation/issues/84
