### ISSUE TITLE
Find dataset for big data performance analysis

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#24]
* Reasonable size, e.g. 1000 documents (?). A dataset too small does not produce reliable results, a dataset too big is not practical
* For start all documents are in English. Would be nice to have to be able to measure and compare speed in other languages also
* statistics about the dataset
    * Amount of words in total / each document
    * Size of dataset in MB in total / each document

[Minutes: Towards processing 100k documents per hour with FREME NER
](https://docs.google.com/document/d/1ipfDmYdxWbvdLTUS096CzC7gRij8T4nGyR-uDr90IUE/edit#heading=h.8uc3osxb3xqi)

**Comment by m1ci** [comment]
To summarize, for big data performance analysis ​one can re-use following datasets:


- N3 corpus dataset: http://aksw.org/Projects/N3NERNEDNIF.html
- DBpedia Spotlight dataset: http://www.yovisto.com/labs/ner-benchmarks/data/dbpedia-spotlight-nif.ttl
- KORE 50 dataset: http://www.yovisto.com/labs/ner-benchmarks/data/kore50-nif-2014-11-03.ttl
- Datasets from the OKE challenge: https://github.com/anuzzolese/oke-challenge/tree/master/evaluation-data
- MSNBC corpus: https://github.com/AKSW/gerbil/blob/e5e471b42ba72775c6e1883415b487cec73830ed/src/main/resources/dataId/corpora/MSNBC.ttl, or
- subset from the wiki links corpus (provided by Google). http://wiki-link.nlp2rdf.org/. It contains 40 million mentions and it is over 180GB in size.

Can we close this issue?

**Comment by jnehring** [comment]
Thank you :)
