### ISSUE TITLE
Improve linking part of FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#27]
* Derived from [Specification of FREME 0.4](https://docs.google.com/document/d/1djp_pkUiAbTaGB8IrXckS_Ngz1j6HqPb3erepYn_htA/edit#), section e-Entity
* Please document your plans here before implementing this task.

**Comment by m1ci** [comment]
This requires more work and will not be part of FREME 0.4.

**Comment by fsasaki** [comment]
@m1ci , the 0.4 specification just refers to this issue and the other way round. Can you give an idea of what work is required and what the time frame is? E.g. FREME 0.5 or later?

**Comment by jnehring** [comment]
We discussed to move this issue to FREME 0.5 when @nilesh-c was in Berlin. Unfortunately there is only a few days left for developing FREME 0.4 and too many features in FREME NER for these few days.
