### ISSUE TITLE
Introduce configuration options for FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#29]
waits for #28

**Comment by jnehring** [comment]
done

**Comment by jnehring** [comment]
Spring configuration is added to FREME NER but it is not yet used by FREME NER.

**Comment by jnehring** [comment]
@nilesh-c is this done? Can you please document the configuration options in http://api-dev.freme-project.eu/doc/knowledge-base/configuration-options.html

**Comment by m1ci** [comment]
This should be already implemented in the java-api branch with https://github.com/freme-project/freme-ner/commit/8a3274900c7e53e3bb02b8014dc390415e6868ef

**Comment by jnehring** [comment]
@m1ci @nilesh-c is this done? Can we close the issue?

**Comment by m1ci** [comment]
done.
