### ISSUE TITLE
Convert CORDIS dataset to LOD

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#31]
https://open-data.europa.eu/en/data/dataset/cordisfp7projects

**Comment by m1ci** [comment]
Done.
Linked Data Fragments endpoint: http://rv2622.1blu.de:5000/cordis
Dump: http://rv2622.1blu.de/datasets/cordis/

**Comment by m1ci** [comment]
added also at datahub.io http://datahub.io/dataset/cordis-corpus
