### ISSUE TITLE
Exclude entities with length of one character

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#35]
We had the idea to exclude links to DBPedia for entities with length 1. We experienced many wrong links to entities like `B`, `.`, `(` and with this strategy we could eliminate all of these wrong links. I can also hardly think of a useful entity that has length one.

This is only a suggestion. Please dont implement it right away in FREME 0.4.

It might be useful to introduce a parameter to switch this behaviour on / off.

**Comment by m1ci** [comment]
there are several options on how we can implement this:
1) black lists of entity mentions
2) black lists of regex filters - I believe with regex we can filter out also entities with length one

**Comment by m1ci** [comment]
@jnehring do you have any example where signs like `B`, `.`, `(` are spotted as entities?

**Comment by jnehring** [comment]
These entities where detected in https://github.com/freme-project/e-Entity/issues/48 and https://github.com/freme-project/e-Entity/issues/43 . There is only one example text that produces an entity "(". Now the API call does not produce this anymore. So I close this issue.
