### ISSUE TITLE
Idea for domain specific topic detection

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#36]
I have the following idea for domain specific topic detection:

To perform a domain specific topic detection, a user first creates his dataset / taxonomy. This is in SKOS format. Then FREME NER performs entity linking against the taxonomy. The taxonomy has properties like `skos:concept` or maybe `rdf:type`. These link each entity against a set of categories. Then we can use the same algorithms that we use for general purpose topic detection for the domain specific topic detection.

The advantage of this approach is that it is the same as general purpose topic detection. One could think of general purpose topic detection as a special case of the domain specific topic detection. We can re-use existing freme technologies (e.g. upload of a SKOS dataset).

What do you think @m1ci @koidl  ?

**Comment by m1ci** [comment]
this issue has been handled with the domain specific NER feature. @jnehring can we close this issue?

**Comment by jnehring** [comment]
we can close it
