### ISSUE TITLE
Exchange FREME NER database to Hibernate

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#38]

**Comment by jnehring** [comment]
@ArneBinder already prepared this task and created database entities and a repository class in FREMECommon repository.

**Comment by m1ci** [comment]
this has been implemented, @nilesh-c please confirm and close this issue.

**Comment by nilesh-c** [comment]
This has been implemented in https://github.com/freme-project/freme-ner/tree/hibernateprobs/ (this is the only branch that needs to merged to master)
