### ISSUE TITLE
Install 2nd Solr Server on freme-worker

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#40]

**Comment by jnehring** [comment]
Is this done? If yes please document the installation of both Solr Servers in [FREME Server Infrastructure](https://docs.google.com/document/d/1PcfGykRqBE2QmH2kuVR8rncTyN4W6o9ZkkfTVz7iPrQ/edit#). Report the ports they run on and include links to management web uis.

**Comment by m1ci** [comment]
this is done

**Comment by jnehring** [comment]
@m1ci did you update the documentation?

**Comment by m1ci** [comment]
updated

**Comment by jnehring** [comment]
Thank you
