### ISSUE TITLE
Berlin is not recognized

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#41]
"Welcome to Berlin" does not recognize Berlin anymore. This used to work.

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.3/e-entity/freme-ner/documents?input=Welcome%20to%20Berlin&informat=text&outformat=turtle&language=en&dataset=dbpedia"
```

produces

```
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .

<http://freme-project.eu/#char=0,17>
        a               nif:String , nif:Context , nif:RFC5147String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "17"^^xsd:int ;
        nif:isString    "Welcome to Berlin"^^xsd:string .

```

The problem occurs on freme-live.

**Comment by m1ci** [comment]
thanks for reporting! We found the cause for this bug, will be fixed soon.

**Comment by m1ci** [comment]
We found out that the bug wasn't related to this issue. If you formulate this as a regular sentence ending with dot sign (.) then Berlin is correctly recognized. Actually the trained model was build on longer and correctly formulated sentences. This for example works: "Welcome to the city of Berlin."
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Welcome%20to%20the%20city%20of%20Berlin.&outformat=turtle&language=en&dataset=dbpedia

**Comment by jnehring** [comment]
Thanks for investigating on this. I move this to #49

**Comment by nilesh-c** [comment]
As I have said before, this is not because of the training or the model itself. This was a bug introduced at the time of implementing confidence scores. This is fixed on ```javaapi3-enhack``` now. That branch has a lot of other stuff (including the Java API and Hibernate code) and will be merged into master soon.
