### ISSUE TITLE
Install two FREME NER instances on freme-worker

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#42]

**Comment by m1ci** [comment]
this is done

**Comment by jnehring** [comment]
We need two versions - one for live and one for dev. This is done also?

**Comment by m1ci** [comment]
> We need two versions - one for live and one for dev.
Ah, this wasn't specified.

> This is done also?
No.

**Comment by jnehring** [comment]
Is this task finished?

**Comment by m1ci** [comment]
yes

**Comment by jnehring** [comment]
Thanks. Please add some documentation to [FREME Server Infrastructure](https://docs.google.com/document/d/1PcfGykRqBE2QmH2kuVR8rncTyN4W6o9ZkkfTVz7iPrQ/edit#heading=h.88j86kgn2x5n)

* Installation folders of the two instances
* Ports that these instances use

**Comment by m1ci** [comment]
done

**Comment by jnehring** [comment]
Thank you
