### ISSUE TITLE
Setup Jenkins to reinstall FREME NER on freme-worker

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#43]

**Comment by m1ci** [comment]
how are we going to separate the FREME NER instances used for FREME live and dev? Is freme-workers going to host only instances for FREME dev or also FREME live? Also, where the instances will run? 2 on freme-workers, 2 on freme-live or freme-dev? What are the plans for the setup?

**Comment by jnehring** [comment]
On freme-worker we will install freme-ner and all its components twice, once for freme-dev and once for freme-live. So there will be two SORL servers running on different ports and two FREME NER instances running on different ports. Also we will have two folders for the stanford NER models. So these two instances are totally separated except for the server they run on.

This issue is about to reinstall the dev version of freme ner.

**Comment by m1ci** [comment]
OK, but FREME live and dev will use same instances of FREME NER?

**Comment by jnehring** [comment]
No we will have two separate instance of FREME NER on freme-worker. One for live and one for dev.

**Comment by m1ci** [comment]
So, the FREME Cloud will use only one FREME NER instance for dev and live, so no load balancing, or?

**Comment by jnehring** [comment]
Yes right. I do not think that we will have time to really scale it out to multiple servers within freme 0.4 development time. Now we provide the technical possibity for scaling out and later on we will do it.

**Comment by m1ci** [comment]
OK, thanks for clarification, makes sense!

**Comment by jnehring** [comment]
This waits for #106, #63

**Comment by m1ci** [comment]
what is #106? and #63 is https://github.com/freme-project/technical-discussion/issues/63?

**Comment by jnehring** [comment]
#63 is wrong. I dont find the issue that I wanted to link to. So lets say it waits for freme-project/Broker#106 only.

@m1ci can you click on the link?

**Comment by m1ci** [comment]
yes, I can, thanks

**Comment by jnehring** [comment]
I started this task yesterday. I stopped freme-ner on freme-dev and I am still struggling to restart it. Hopefully I can fix this today.

**Comment by jnehring** [comment]
done
