### ISSUE TITLE
Incompatibility of Spring Cloud and SolrJ

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#45]
In the cloud branch in the broker I created a simple REST endpoint that uses the FREME NER library that we developed together. But it does not work.

So I run eu.freme.broker.FremeNERStarter and it starts a REST API with FREME NER. Then I call
``` 
POST http://localhost:8081/e-entity/freme-ner/documents?informat=turtle&language=de&dataset=dbpedia&outformat=turtle&rdfPrefix=http://freme-project.eu

@prefix nif:<http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
<http://example.org/document/1#char=0,21>
  a nif:String , nif:Context, nif:RFC5147String ;
  nif:isString "Welcome to Berlin"^^xsd:string;
  nif:beginIndex "0"^^xsd:nonNegativeInteger;
  nif:endIndex "21"^^xsd:nonNegativeInteger;
  nif:sourceUrl <http://differentday.blogspot.com/2007_01_01_archive.html>.
```

The result is that the java process terminates. This is critical behaviour. Until now we never had an error that crashes the whole system. We only had errors that crash single API calls.

In the attachment I put the error log. 

[freme-ner-error.txt](https://github.com/freme-project/freme-ner/files/13917/freme-ner-error.txt)

**Comment by jnehring** [comment]
To reproduce the error:

* git clone broker and "cloud" branch
* install broker - it will pull in freme-ner dependency from our maven repository this is the state of "javaapi" branch
* then start broker with main class `eu.freme.broker.FremeNERStarter`

Then do above api call.

**Comment by jnehring** [comment]
Old versions of spring boot are not compatible with SolrJ 5:

https://jira.spring.io/browse/DATASOLR-228
https://jira.spring.io/browse/DATASOLR-232

I tried to update Spring Boot but I did not succeed. It is closely coupled to Spring Cloud which uses an older version of Spring Boot.

@nilesh-c is it possible to downgrade the SolrJ Client to Solr 4.7.2 ?

**Comment by m1ci** [comment]
I tried to downgrade FREME NER to Solrj to 4.7.2 but this will require significant changes in the code and also I'm not 100% sure if this will work since this client library is also bound to the actual Solr implementation we are using.
What about upgrading Spring Cloud and Spring Boot? - It seems Sprint is still not compatible with SolrJ 5.xxx? or?

**Comment by jnehring** [comment]
Lets leave this topic for now. The information that a downgrade of SolrJ is difficult also is enough right now.

**Comment by jnehring** [comment]
In FREME 0.5 we will not use Spring cloud. Therefore the incompatibility does not occur and we do not need to solve this problem in FREME 0.5.

**Comment by m1ci** [comment]
@jnehring should we still keep this issue open?

**Comment by jnehring** [comment]
I was playing around with FREME NER and the issue occured again. So I copied the bugfix from SpringBoot to exclude SolrJ Autoconfiguration from https://github.com/spring-projects/spring-xd/pull/1797

Lets leave this open to see if it really does not come back.

**Comment by jnehring** [comment]
This is no longer a problem
