### ISSUE TITLE
Improve NER on short text

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#49]
The Berlin entity in `Welcome to Berlin` is not recognized. When the sentence ends with a dot, then the entity is recognized. Thats because Stanford NER was training on "normal" text with dots. Maybe we can find a workaround like inserting dots at the end of short text that does not have `.`, `!`, `?` or similar.

**Comment by pheyvaer** [comment]
It would be useful for the CKEditor if this gets fixed.

**Comment by nilesh-c** [comment]
Fixed this on the ```javaapi3-enhack``` branch. Will be able to test this once the new REST API is up.

**Comment by m1ci** [comment]
fixed, see http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Welcome%20to%20Berlin&outformat=turtle&language=en&dataset=dbpedia
