### ISSUE TITLE
HTTP authentication for Solr instances

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#50]

**Comment by jnehring** [comment]
This task will be implemented by @nilesh-c as discussed in [2015-11-26 telco on FREME NER](https://docs.google.com/document/d/1KbWPOrLbz_B3UV9fyMj1LVuwQDHhdMcXGmSpF22JYio/edit#)

**Comment by nilesh-c** [comment]
@jnehring Instead of complicating this, I propose simply running Solr on localhost (like MySQL) and not exposing it on the public IP. To perform SOLR admin tasks one can use port-forwarding.

This will require a solr restart. Couple minutes.

**Comment by jnehring** [comment]
> Instead of complicating this, I propose simply running Solr on localhost (like MySQL) and not exposing it on the public IP. To perform SOLR admin tasks one can use port-forwarding.

When we do this then we can no longer access the Solr Web Interface. @nilesh-c do you use the Solr web interface sometimes? When you dont need it then this sounds like a good solution.

**Comment by m1ci** [comment]
I would stay with: HTTP basic auth for access from public IP, no auth for localhost

**Comment by jnehring** [comment]
> I would stay with: HTTP basic auth for access from public IP, no auth for localhost

+1

**Comment by m1ci** [comment]
I have secured both Solr instances. I had to do following changes:
- Solr dev dashboard at http://rv2622.1blu.de/solrdev/
- Solr live dashboard at http://rv2622.1blu.de/solrlive/

Both dashboards are secured now.
