### ISSUE TITLE
Cleanup pom.xml

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#51]
The pom.xml of FREME NER is very long and I do not know what functionality is inside. There is a problem with the packaging which is set to "pom". We need "jar" packaging.

When I set packaging to "jar" then I see some error message in pom.xml.

So the pom.xml needs to be debugged. I assume that we can delete some parts.

**Comment by m1ci** [comment]
this should be fixed, please check.

**Comment by jnehring** [comment]
fixed. thank you
