### ISSUE TITLE
Make FREME NER a Java API

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#52]
There is an implementation in https://github.com/freme-project/freme-ner/tree/javaapi

I am not sure if it is finished. I dont know if all features are covered by the Java API. At least it needs to be merged in the master branch.

Some unit tests would be really useful. They help finding errors and also document how to use the Java API.

**Comment by m1ci** [comment]
this has been implemented - next step is to integrate it the Broker.
