### ISSUE TITLE
Add dataset upload script

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#53]
Please add the dataset upload script to FREME NER repository. Also add a short description including example call to the readme file.

**Comment by jnehring** [comment]
@nilesh-c is this finished? I cannot find the script.

**Comment by m1ci** [comment]
Here are two script examples for uploading data:
https://github.com/freme-project/freme-ner/blob/master/indexorcid.py
https://github.com/freme-project/freme-ner/blob/master/indexviaf.py

**Comment by m1ci** [comment]
@jnehring 
here is one more script for indexing library of congress data
https://github.com/freme-project/freme-ner/blob/master/index-loc-authors.py
