### ISSUE TITLE
Talk to Gerbil developers

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#54]
In [2015-11-26 call on FREME NER](https://docs.google.com/document/d/1KbWPOrLbz_B3UV9fyMj1LVuwQDHhdMcXGmSpF22JYio/edit?usp=drive_web) @m1ci said he will ask the developers of Gerbil if they can release the parts of Gerbil that we use under an open source license. Then we can copy these codes.

When we can do this we would solve #39 and https://github.com/freme-project/technical-discussion/issues/82

**Comment by m1ci** [comment]
this issue is solved. the part using Gerbil has been re-implemented and currently there is not dependency on Gerbil anymore.

**Comment by jnehring** [comment]
There is still the gerbil jar in the lib folder. I assume this can be deleted?

**Comment by m1ci** [comment]
yes, it can be removed.

**Comment by jnehring** [comment]
done
