### ISSUE TITLE
FREME NER fails

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#55]
FREME NER on freme-dev does not work any more. On freme-live it still works.

You can use this URI to verify it is crashed:

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Welcome%20to%20Berlin!&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all

https://github.com/freme-project/Broker/issues/146 indicates the problem is that freme-ner crashed on freme-worker.

**Comment by m1ci** [comment]
fixed. Sorry for the inconvenience.
