### ISSUE TITLE
OOM in FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#56]
The crash in https://github.com/freme-project/freme-ner/issues/55 was caused by an OutOfMemory exception of FREME NER on freme-worker. This issue is a reminder to further examine this.

* How much RAM is configured for FREME NER?
* We should increase maximum heap size (-Xmx) for FREME NER.
* Maybe we can save memory when freme-dev loads only english models and freme-live loads all models for named entity spotting and classification.

**Comment by jnehring** [comment]
any update here?

**Comment by m1ci** [comment]
> How much RAM is configured for FREME NER?
> We should increase maximum heap size (-Xmx) for FREME NER.

Both, freme ner live and dev are configured (-Xmx) configured with 32GB.

> Maybe we can save memory when freme-dev loads only english models and freme-live loads all models for named entity spotting and classification.

Lets leave it as it is now. If the problem occurs again, we can consider loading only the english models at the dev instance.

**Comment by jnehring** [comment]
> Both, freme ner live and dev are configured (-Xmx) configured with 32GB.

This causes problems because we only have 48 GB Ram in total. We should set -Xmx for all applications (2x FREME NER, 2x Solr, Virtuoso) so they consume 44 GB in total. Then there are still 4 GB left for the operating system and also for the memory usage of java applications that is not heap space.
So I think this configuration is the source of the OOM exception.

> Lets leave it as it is now. If the problem occurs again, we can consider loading only the english models at the dev instance.
fine for me.

**Comment by jnehring** [comment]
@m1ci Did you change the memory configuration in FREME worker?

**Comment by m1ci** [comment]
not, I left as it is now. I thought we agreed on:

> Lets leave it as it is now. If the problem occurs again, we can consider loading only the english models at the dev instance.

**Comment by jnehring** [comment]
I thought "Lets leave it as it is now." refers to loading english models only for freme-dev to save memory.

Lets open the task again when we have another OutOfMemoryException. The issue does not seem to be so urgend.

**Comment by m1ci** [comment]
> Lets open the task again when we have another OutOfMemoryException. The issue does not seem to be so urgend.

Agree.
