### ISSUE TITLE
Odd annotation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#57]
This curl

```
curl -X POST  --header "Content-Type:" --header "Accept: text/n3" -d @text.txt "http://api.freme-project.eu/0.4/e-entity/freme-ner/documents?informat=text&outformat=json-ld&language=de&dataset=dbpedia&mode=spot" > out2.txt`` `
```

([test.txt here](https://github.com/freme-project/freme-ner/files/61247/test.txt)) produces an odd annotation:

```
{
    "@id" : "http://freme-project.eu/#char=0,0",
    "@type" : [ "nif:RFC5147String", "nif:String", "nif:Phrase", "nif:Word" ],
    "nif:anchorOf" : "",
    "beginIndex" : "0",
    "endIndex" : "0",
    "referenceContext" : "http://freme-project.eu/#char=0,10533",
    "taConfidence" : "NaN"
  }
```

* taConfidence is NaN - this does not make sense
* beginIndex and endIndex are both 0 - does not make sense either

**Comment by nilesh-c** [comment]
Fixed in dev. Please check and close issue.

**Comment by m1ci** [comment]
I confirm its fixed - try: `curl -X POST  --header "Content-Type:" --header "Accept: text/n3" -d @text.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text&outformat=json-ld&language=de&dataset=dbpedia&mode=spot" > out.txt`

**Comment by jnehring** [comment]
I tried, I still get the odd annotation:

```
  "@graph" : [ {
    "@id" : "http://freme-project.eu/#char=0,0",
    "@type" : [ "nif:RFC5147String", "nif:String", "nif:Phrase", "nif:Word" ],
    "nif:anchorOf" : "",
    "beginIndex" : "0",
    "endIndex" : "0",
    "referenceContext" : "http://freme-project.eu/#char=0,10533",
    "taConfidence" : "NaN"
```

**Comment by m1ci** [comment]
are you using the text you provided
https://github.com/freme-project/freme-ner/files/61247/test.txt
and the curl command I provided in the previous comment?

**Comment by jnehring** [comment]
Sorry I was testing FREME 0.4 instead of the dev api. When I test freme-dev the problem does not occur. So the bug is solved.
