### ISSUE TITLE
Create dataset does not work on freme-dev

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#58]
This CURL
```
curl -X POST --header "Content-Type: text/n3" --header "Accept: application/json" -d "   \"101 Communications\" .
   \"101 Communications, Inc\" .
   \"101 Communications, LLC\" .
   \"101communications\" .
   \"2Cs Communications\" .
   \"2x4 (Design studio)\" .
" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?informat=n-triples&name=jan-test&description=this%20is%20a%20test%20dataset&language=de"
```

produces

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-entity/freme-ner/datasets",
  "message": "500 Internal Server Error",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1451997783314
}
```

Also the unit tests fail (see attachments).

[error.txt](https://github.com/freme-project/freme-ner/files/78404/error.txt)

Yesterday I reloaded the Solr Core of freme-dev. Since the reload I there are many error reports in the logfiles in the Solr Admin UI. I reloaded the core in order to empty the cache (see https://github.com/freme-project/load-testing/issues/2). Maybe there is a connection to the error?

@nilesh-c I have no idea how to proceed. Can you please take a look at the problem?

**Comment by nilesh-c** [comment]
I'm not familiar with ```application/json```. @m1ci could you check if the input looks OK here or not? I tried creating a test dataset (with whole of global airports in it). It timed out, but the dataset got created with about 1/3rd of the entities in them. The solr logs aren't too helpful either. Will take another look in the evening.

**Comment by m1ci** [comment]
@jnehring the input seems weird. Is it valid RDF?

@nilesh-c the global airports is quite small with about 5 MB. It should be processed successfully. Also, indexing just 1/3rd of the entities is not OK. please check this.

**Comment by jnehring** [comment]
I copied the CURL generated by the API tester: http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/createDataset. It dsplayed the wrong data, actually I send this RDF to FREME:

```
 <http://www.lib.ncsu.edu/ld/onld/00000326 > <http://www.w3.org/2004/02/skos/core#prefLabel > "101 Communications" .
 <http://www.lib.ncsu.edu/ld/onld/00000326 > <http://www.w3.org/2004/02/skos/core#altLabel > "101 Communications, Inc" .
 <http://www.lib.ncsu.edu/ld/onld/00000326 > <http://www.w3.org/2004/02/skos/core#altLabel > "101 Communications, LLC" .
 <http://www.lib.ncsu.edu/ld/onld/00000326 > <http://www.w3.org/2004/02/skos/core#altLabel > "101communications" .
 <http://www.lib.ncsu.edu/ld/onld/00001273 > <http://www.w3.org/2004/02/skos/core#prefLabel > "2Cs Communications" .
 <http://www.lib.ncsu.edu/ld/onld/00000842 > <http://www.w3.org/2004/02/skos/core#prefLabel > "2x4 (Design studio)" .
```

**Comment by nilesh-c** [comment]
@jnehring the RDF you pasted is wrong (spaces between URI and >). Maybe try this file:
[onld.txt](https://github.com/freme-project/freme-ner/files/89132/onld.txt)

This request works:
curl -d@onld.txt -X POST "http://rv2622.1blu.de:8080/api/datasets?name=testdataset_ondl&properties=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%2Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23altLabel"
{
  "Status": "Dataset created successfully.",
  "DatasetInfo": {
    "Name": "testdataset_ondl",
    "Description": "",
    "TotalEntities": "6",
    "CreationTime": "1452700221941"
  }

BTW, not sure why solr is running on 4g memory right now. Did someone restart it without the -m option?

**Comment by jnehring** [comment]
The CURL I provided has a copy & paste error. The body of the request is the example from the API doc. Now the error message has changed. I move the issue to #68
