### ISSUE TITLE
character encoding bug

### ISSUE THREAD

**Issue by PeterBourgonje** [freme-project/freme-ner#59]
I'm having some issues with character encoding. My input is in utf-8, but the result from the following curl doesn't contain the same number of characters as my input:

curl -v -d @C:\Users\pebo01\Desktop\debug.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=turtle&outformat=turtle&language=de&dataset=dbpedia&mode=link" -H "Content-Type:"

debug.txt is attached.
As you can see, in there, for the total string, it says:
<http://dkt.dfki.de/examples/#char=0,782>

whereas in the curl response, I get:
<http://freme-project.eu/#char=0,776>

[debug.txt](https://github.com/freme-project/freme-ner/files/87432/debug.txt)

**Comment by m1ci** [comment]
thanks for reporting. it seems, along the processing some component is removing the newlines. we need to debug this. stay tuned.

**Comment by m1ci** [comment]
Hi Pieter,
we investigated the issue and we found out that this is not issue of the service, neither of FREME NER nor e-Entity, but its a normal behaviour of the cURL client.
According to the cURL spec for the `-d` (`--data`) parameter:
> When --data is told to read from a file like that, carriage returns and newlines will be stripped out.
This means that newlines and and returns are removed before sending to the client.

To avoid this behaviour, instead of using `-d` (`--data`) you can use the `--data-binary` parameter. By using this parameter the newlines and the returns will not be removed before sending the content to the client.
This is also documented in the cURL spec for the `--data-binary` parameter:
> If you start the data with the letter @, the rest should be a filename. Data is posted in a similar manner as --data-ascii does, except that newlines and carriage returns are preserved and conversions are never done.

Does this solve your issue?

**Comment by PeterBourgonje** [comment]
Hi Milan,
Thanks a lot for the clarification!
That seems to explain the issue with the curl post. Unfortunately I cannot reproduce anything at the moment, because I get a "bad gateway" error with the exact same post as the one above (which produced relevant output before). 
Could it be that the service is down temporarily, because of the architecture update? (unfortunately my curl response just says bad gateway/502/ExternalServiceFailedException, without any additional information as to what went wrong.

However, the curl statement was just to (minimally) reproduce the issue.
In my code I'm using the following line:
String fremeNERresult = callFremeNER(nifString, "de", "http://dkt.dfki.de/examples/#", "dbpedia", 1, mode, "TTL");
(If I try that, I currently also get a ExternalServiceFailedException)
Would you know if there is any way to provide the equivalent of the --binary option in java code?

**Comment by m1ci** [comment]
> Could it be that the service is down temporarily, because of the architecture update? (unfortunately my curl response just says bad gateway/502/ExternalServiceFailedException, without any additional information as to what went wrong.

Yes! We do last minute updates at the dev API, and only the English version is enabled at the moment. However you can validate it using the FREME production API. Not using the http://api-dev.freme-project.eu/current/ but use the http://api.freme-project.eu/0.4/ endpoint instead.
Try:
> curl -v --data-binary @debug-5.txt "http://api.freme-project.eu/0.4/e-entity/freme-ner/documents/?informat=turtle&outformat=turtle&language=en&dataset=dbpedia&mode=link" -H "Content-Type:"

**Comment by PeterBourgonje** [comment]
Yep, great, that works! (at least for the curl part) Any idea how/if I can provide the binary flag to the java code?

**Comment by m1ci** [comment]
No need to provide the binary flag in Java. The issue we have here is with the cURL client (removing newlines/returns). A Java client should submit the content in its original form.

**Comment by m1ci** [comment]
the issue has been identified and related to curl. Closing the issue now. If needed more support, feel free to reopen it.
