### ISSUE TITLE
Types not consistent

### ISSUE THREAD

**Issue by ghsnd** [freme-project/freme-ner#60]
See also freme-project/Semantic-Book#25

In the following example, **Patisia** (a neighbourhood of Athens) is detected as a `Location` *and* a `Person`.

**Text:**

*The municipality of Athens, the city centre of the Athens Urban Area, is divided into several districts: Omonoia, Syntagma, Exarcheia, Agios Nikolaos, Neapolis, Lykavittos, Lofos Strefi, Lofos Finopoulou, Lofos Filopappou, Pedion Areos, Metaxourgeio, Aghios Kostantinos, Larissa Station, Kerameikos, Psiri, Monastiraki, Gazi, Thission, Kapnikarea, Aghia Irini, Aerides, Anafiotika, Plaka, Acropolis, Pnyka, Makrygianni, Lofos Ardittou, Zappeion, Aghios Spyridon, Pangration, Kolonaki, Dexameni, Evaggelismos, Gouva, Aghios Ioannis, Neos Kosmos, Koukaki, Kynosargous, Fix, Ano Petralona, Kato Petralona, Rouf, Votanikos, Profitis Daniil, Akadimia Platonos, Kolonos, Kolokynthou, Attikis Square, Lofos Skouze, Sepolia, Kypseli, Aghios Meletios, Nea Kypseli, Gyzi, Polygono, Ampelokipoi, Panormou-Gerokomeio, Pentagono, Ellinorosson, Nea Filothei, Ano Kypseli, Tourkovounia-Lofos Patatsou, Lofos Elikonos, Koliatsou, Thymarakia, Kato Patisia, Treis Gefyres, Aghios Eleftherios, Ano Patisia, Kypriadou, Prompona, Aghios Panteleimonas, Pangrati, Goudi and Ilisia.*

**Nif output:**

```
...
<http://freme-project.eu/#char=975,986>
        a                     nif:String , nif:Word , nif:Phrase , nif:RFC5147String ;
        nif:anchorOf          "Ano Patisia"^^xsd:string ;
        nif:beginIndex        "975"^^xsd:int ;
        nif:endIndex          "986"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,1058> ;
        itsrdf:taClassRef     <http://nerd.eurecom.fr/ontology#Location> ;
        itsrdf:taConfidence   "0.8791036558879513"^^xsd:double ;
        itsrdf:taIdentRef     dbpedia:Patisia .

<http://freme-project.eu/#char=926,938>
        a                     nif:Phrase , nif:RFC5147String , nif:Word , nif:String ;
        nif:anchorOf          "Kato Patisia"^^xsd:string ;
        nif:beginIndex        "926"^^xsd:int ;
        nif:endIndex          "938"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,1058> ;
        itsrdf:taClassRef     <http://nerd.eurecom.fr/ontology#Person> ;
        itsrdf:taConfidence   "0.8724703771684201"^^xsd:double ;
        itsrdf:taIdentRef     dbpedia:Patisia .
...
```

Note that they both point to the same page [dbpedia:Patisia](http://dbpedia.org/page/Patisia), where there is even no type `Person` mentioned.

**Comment by m1ci** [comment]
the types http://nerd.eurecom.fr/ontology#Person and http://nerd.eurecom.fr/ontology#Location are not from DBpedia, but from StanfordNER.

**Comment by m1ci** [comment]
@ghsnd what you want to report is that the types Person and Location are wrong, right?

**Comment by ghsnd** [comment]
> @ghsnd what you want to report is that the types Person and Location are wrong, right?

What I wanted to report is that:

* Patisia is a location, not a person. It does not really matter if it's a Stanford or a DBpedia location :)
* The fact that the same entity is recognised as a person as well as a location seems strange.

**Comment by jnehring** [comment]
These misclassifications happen. We cannot do better then this. So I close this issue.
