### ISSUE TITLE
NER to return full label from used datasets?

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/freme-ner#62]
Hello guys,

I was trying some example calls with the VIAF and ORCID datasets and I think it would be very useful if the service would also include the full labels for the annotated terms returned from the selected dataset each time. For example, sometimes in our case we get author elements like this:

_"Stoitsis, Inst. for Byzantine Research, Athens, Greece"_

The [output](http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Stoitsis,%20Inst.%20for%20Byzantine%20Research,%20Athens,%20Greece&informat=text&outformat=turtle&language=en&dataset=viaf&mode=all) of the service for the above (having selected "VIAF") annotates "Byzantine Research" with the VIAF URI, which of course is not the full name of the institute. Is it possible to add another element to the output that displays the full label of the term retrieved from the dataset (ie. "_Institute of Byzantine Research_")?

**Comment by m1ci** [comment]
Actually, you can retrieve this info - the full name - using e-Link.
Or would it be more comfortable for you to get also the name in the FREME NER output?

**Comment by Katsivelisp** [comment]
Hi,

I think it would be more comfortable for us if also had the full name in the FREME NER output. This would also reduce the FREME API calls on our end, no? 

This of course is not of great importance at he moment. But in any case thank you for your support. :)

**Comment by fsasaki** [comment]
@m1ci , this is only out of curiosity and not urgent:

> Actually, you can retrieve this info - the full name - using e-Link.

Do you have an example query to achieve this?

**Comment by m1ci** [comment]
@fsasaki I've crafted template which enriches VIAF URIs with their corresponding label. Here it is
http://api-dev.freme-project.eu/current/e-link/templates/4472?outformat=json

Here is cURL example with use of the template:

``
curl -v "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Stoitsis,%20Inst.%20for%20Byzantine%20Research,%20Athens,%20Greece&informat=text&outformat=turtle&language=en&dataset=viaf&mode=all" | curl -d @- "http://api-dev.freme-project.eu/current/e-link/documents?templateid=4472" -H "Content-Type:text/turtle"
``

First, it performs NER using VIAF, then it enriches the content with e-Link

> I think it would be more comfortable for us if also had the full name in the FREME NER output. This would also reduce the FREME API calls on our end, no?

Correct, it will reduce the calls on the client side. I think adding label (where possible) for entities makes sense - we will consider this.

**Comment by fsasaki** [comment]
Very cool! Thanks for showing this, Milan.

**Comment by jnehring** [comment]
#92 is very similar.

**Comment by jnehring** [comment]
implemented through #92
