### ISSUE TITLE
FREME NER crashed?

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#64]
This API call

curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Welcome%20to%20Berlin&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=all"

produces this result:
```
{
  "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
  "path": "/e-entity/freme-ner/documents",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1454333929089
}
```
The log says

```
ERROR   2016-02-01 14:32:33,157 [http-nio-8084-exec-22] eu.freme.broker.tools.ExceptionHandlerService  - Request: http://rv1443.1blu.de:8084/e-entity/freme-ner/documents raised
eu.freme.broker.exception.ExternalServiceFailedException
        at eu.freme.broker.eservices.FremeNER.execute(FremeNER.java:237)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
```

Maybe the FREME NER service has crashed?

**Comment by jnehring** [comment]
Fixed. I think @m1ci restarted FREME NER.

**Comment by Katsivelisp** [comment]
Hey guys, service seems to be down again.

**Comment by Katsivelisp** [comment]
Nevermind, I guess I reached my limit for today.

**Comment by jnehring** [comment]
Hey. No you did not reach your limit. We disabled rate limiting on both freme-dev and freme-live

**Comment by Katsivelisp** [comment]
Yes, apparently we had some network issues yesterday. Sorry for the false alarm. :)
