### ISSUE TITLE
Hard coded paths for models

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#66]
There is some hard coded paths [here](https://github.com/freme-project/freme-ner/blob/07ec460e1db92c932f1ef4210b00db95782c0d67/src/main/scala/org/elinker/core/api/service/EntityApiService.scala#L23-L30) that should by stored in a properties files.

**Comment by m1ci** [comment]
This is handled with https://github.com/freme-project/freme-ner/blob/master/src/main/resources/applicationContext.xml#L31
