### ISSUE TITLE
Broken link for models

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#67]
Hi,
I've tried to download the follow models, but I can get it  through http://freme.aksw.org/datasets/ner-trained-models/wikiner/ (503 - Service Unavailable)

Models:
wikiner-en-ner-model.ser.gz
wikiner-it-ner-model.ser.gz
wikiner-nl-ner-model.ser.gz
wikiner-fr-ner-model.ser.gz
wikiner-es-ner-model.ser.gz
wikiner-ru-ner-model.ser.gz

Could you, please, help me on it?

Thank you in advance.

**Comment by m1ci** [comment]
Hi Sandro,

it seems the freme.aksw.org is down.
I'll try to fix this by uploading the models somewhere else.

Stay tuned,
Milan

--
Milan Dojchinovski
http://dojchinovski.mk

**Comment by jnehring** [comment]
Is this issue fixed? Can we close the issue?

**Comment by m1ci** [comment]
its fixed
