### ISSUE TITLE
Unclear taClassRef in FREME NER with CORDIS dataset

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/freme-ner#72]
Hello,

I think we have discussed this issue before with @m1ci. I will try to give a better picture with an example. I'm calling the FREME NER for the following publication abstract with the dataset option set to "**cordis-fp7**":

"_Biodiversity conservation is an urgent task for our society with special attention for grassland areas The EU FP7 research project BIOBIO - INDICATORS FOR BIODIVERSITY IN ORGANIC AND LOW-INPUT FARMING SYSTEMS aims at developing scientifically sound, useful and attractive biodiversity indicators for organic and low-input farming in Europe._"

As you can see from the [response](http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Biodiversity%20conservation%20is%20an%20urgent%20task%20for%20our%20society%20with%20special%20attention%20for%20grassland%20areas%20The%20EU%20FP7%20research%20project%20BIOBIO%20-%20INDICATORS%20FOR%20BIODIVERSITY%20IN%20ORGANIC%20AND%20LOW-INPUT%20FARMING%20SYSTEMS%20aims%20at%20developing%20scientifically%20sound,%20useful%20and%20attractive%20biodiversity%20indicators%20for%20organic%20and%20low-input%20farming%20in%20Europe.&informat=text&outformat=json-ld&language=en&dataset=cordis-fp7&mode=all&type=http://dbpedia.org/ontology/ResearchProject), FREME returns 5 results from the CORDIS dataset marked as **projects** (http://dbpedia.org/ontology/ResearchProject). Two of the results seem correct for this case: 

`{
@id: "http://freme-project.eu/#char=131,137",
@type: [
"nif:String",
"nif:Word",
"nif:Phrase",
"nif:RFC5147String"
],
nif:anchorOf: "BIOBIO",
beginIndex: "131",
endIndex: "137",
referenceContext: "http://freme-project.eu/#char=0,340",
taClassRef: [
"http://dbpedia.org/ontology/ResearchProject",
"http://nerd.eurecom.fr/ontology#Organization"
],
itsrdf:taConfidence: 0.426075815451938,
taIdentRef: "http://www.freme-project.eu/datasets/cordis/projects/90980"
},`

`{
@id: "http://freme-project.eu/#char=155,200",
@type: [
"nif:Phrase",
"nif:RFC5147String",
"nif:String",
"nif:Word"
],
nif:anchorOf: "BIODIVERSITY IN ORGANIC AND LOW-INPUT FARMING",
beginIndex: "155",
endIndex: "200",
referenceContext: "http://freme-project.eu/#char=0,340",
taClassRef: [
"http://nerd.eurecom.fr/ontology#Person",
"http://dbpedia.org/ontology/ResearchProject"
],
itsrdf:taConfidence: 0.5487604842975776,
taIdentRef: "http://www.freme-project.eu/datasets/cordis/projects/90980
}`

This first result has correctly annotated "BIOBIO" as [a FP7 project](http://cordis.europa.eu/project/rcn/90980_en.html). However, as you can probably see, the confidence score is very low/lower than the rest. Also, in taClassRef, we find that BIOBIO is also of type "http://nerd.eurecom.fr/ontology#Organization", which doesn't make much sense. The second correct result strangely enough has a better score, although it matches another part of the project's name. But again, the annotated String is also of type "http://nerd.eurecom.fr/ontology#Person", which doesn't make sense.

Now, take a look at the rest of the results. There is one which with an ideal confidence score (>0.9) that is of type "http://nerd.eurecom.fr/ontology#Location" and is apparently a **false positive**. Such cases come up in approximately 90% of our tests.

Sometimes it makes sense to know the flavors of annotated entities, but in most cases, this creates confusion, especially when confidence scores vary from case to case. Also, please note that in most cases that we have tried, although the project name is explicitly referenced in the input string, it rarely gets recognized by the service or it is assigned a very low confidence score (see the first result).

Do you have any idea on how we could probably "see-through" the false positives in our client? Is there a specific option in the call that will help us narrow-down results to the correct ones? 

Also, on your side, could you confirm what part of the CORDIS entries are matched through our queries? In the [CORDIS projects website](http://cordis.europa.eu/projects/home_en.html), users are given the option to browse through the projects through their acronyms. Just an idea: FREME could probably assign highest confidence scores to entities that match these acronyms. What do you think?

**Comment by m1ci** [comment]
Hi Panagis,
sorry for the late reply.
I answered your question in a separate email. Let me share with the others our conversation:

> Why are the confidence scores so low in some cases?

Because there is low confidence that word/sequence of words being of type LOC/PER/ORG/MISC.​
 
> From the evaluation results that you've run, is there any recommended confidence threshold for projects spotting?

No, I did not do such analysis. However this is a very valid question. We need to tackle it definitely.

> Can you give us a better picture on the itsrdf:taClassRef property? Sometimes spotted projects are also annotated with http://nerd.eurecom.fr/ontology#Organization or other classes.

At the moment the types: ​http://nerd.eurecom.fr/ontology#Organization
http://nerd.eurecom.fr/ontology#Location
http://nerd.eurecom.fr/ontology#Person
and
http://www.w3.org/2002/07/owl#Thing
are the one we get from the entity spotter/classifier.
The rest of types are from a knowledge base you selected (cordis, dbpedia, orcid, etc.). For example http://dbpedia.org/ontology/ResearchProject is from the CORDIS FP7 dataset.
 
> Does it make sense to analyze these on our end in order to get better results?

​I don't think it makes sense. Since our model for spotting entities was trained on data which did not contain project names, but mostly PER, ORG, LOC and MISC (for everything else).

Since we have already some training data (the 57 abstracts)​, we might try to train a model, but I doubt it will work - 57 abstracts are very little.

**Comment by m1ci** [comment]
@Katsivelisp do you need any more support  on this?

**Comment by Katsivelisp** [comment]
@m1ci Thank you very much. No, for now it's fine. Do we have an approximate date/timeline for incorporating these improvements into the existing FREME API?

**Comment by m1ci** [comment]
> @m1ci Thank you very much. No, for now it's fine. Do we have an approximate date/timeline for incorporating these improvements into the existing FREME API?

What improvements?

**Comment by Katsivelisp** [comment]
I'm sorry. I thought that the slight improvement you did on the project spotting case with CORDIS was to be deployed as part of FREME NER at some point.

**Comment by fsasaki** [comment]
Panagis, does this issue still need work?

2016-03-04 12:49 GMT+01:00 Katsivelisp <notifications@github.com>:

**Comment by Katsivelisp** [comment]
@fsasaki I'm sorry for the late response, I was away last week. 

It seems to me that the example I gave above returns the same results (false positives etc). I will try to run full-scale examples in the next few days and let you know.

**Comment by jnehring** [comment]
@Katsivelisp what is the status here? Can we close the issue?

**Comment by m1ci** [comment]
inactive issue, closing it
