### ISSUE TITLE
FREME NER heavy load

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#73]
In the last days we experienced some difficulties with FREME NER. Now it runs fine.

During debugging @m1ci assumed that Wripls heavy API consumption lead to the problems. So we asked Wripl and @xFran to slow down the API consumption.

During load testing we did not experience that heavy load crashes FREME NER. But some changes have been made to FREME NER since we did load testing.

@m1ci does this still hold? Can Wripl return to original speed?

**Comment by m1ci** [comment]
> @m1ci does this still hold? Can Wripl return to original speed?

please stay with the current setup and process one document at a time.

**Comment by jnehring** [comment]
We will examine this further during FREME 0.6
