### ISSUE TITLE
ExternalServiceFailedException when processing HTML

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-ner#76]
When I do the following curl command I get the `ExternalServiceFailedException`. Can anybody tell we why it is not working for my 'special' case?

`curl -X POST --header "Content-Type: text/html" --header "Accept: text/n3" --data "@SB50
.html" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"

The file I used is [SB50.zip](https://github.com/freme-project/freme-ner/files/133952/SB50.zip)

**Comment by m1ci** [comment]
we are re-deploying freme ner.

**Comment by pheyvaer** [comment]
@m1ci can you let me know when it's up again?

**Comment by m1ci** [comment]
yes, will do.

**Comment by m1ci** [comment]
its up again.
