### ISSUE TITLE
FREME NER crashed

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#77]
FREME NER is no longer reachable. I think it has crashed on FREME worker. 

http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=de&dataset=dbpedia&informat=text&input=Welcome+to+Berlin!&outformat=turtle

produces

```
{
  "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
  "path": "//e-entity/freme-ner/documents",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1455704767565
}
```

**Comment by m1ci** [comment]
we needed to redeploy freme ner in order to solve https://github.com/freme-project/freme-ner/issues/50
Very soon it will up and running again.

**Comment by m1ci** [comment]
its up and running again.
