### ISSUE TITLE
Error if output format is text/html with text/html input

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-ner#78]
The same call as in issue #76, however this time we ask to output the result using text/html. However, we get the following error
```
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Feb 17 16:02:27 CET 2016</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>String index out of range: -14</div></body></html>
```
What exactly is the problem here?

P.S. According to the w3 validator our document is valid (beside some deprecated elements, however, that should not make a difference I think).

**Comment by m1ci** [comment]
this issue is related to e-Internationalization service so I moved it https://github.com/freme-project/e-Internationalization/issues/35
