### ISSUE TITLE
numLinks parameter in freme-ner

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#80]
I am working on #79 and discovered the numLinks parameter. It is used in the codes but it is not documented. @m1ci what does the parameter do?

**Comment by m1ci** [comment]
using the numLinks parameter one can specify the number of links to be assigned to an entity. E.g., user can set it to 5, and in a post-editing step he can choose the correct link. By default, only one link is returned, the one with the highest confidence.

**Comment by jnehring** [comment]
@josauder please add the numLinks parameter to the swagger.yaml. Add this text:

Using the numLinks parameter one can specify the maximum number of links to be assigned to an entity. By default only one link is returned. The maximum possible number for this parameter is 5.
