### ISSUE TITLE
FREME NER crashes

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#83]
Sometimes FREME NER crashes. So it does not crash only the current HTTP request but it terminates the whole Java application. This should not happen. I found in the logfiles

[ERROR] [03/18/2016 14:06:48.787] [api-akka.actor.default-dispatcher-6] [ActorSystem(api)] Uncaught error from thread [api-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled

So I want to investigate what `akka.jvm-exit-on-fatal-error` means and if we can set it to another value for better stability.

**Comment by sandroacoelho** [comment]
hI @jnehring. I will investigate this issue asap and then provide a solution.

**Comment by jnehring** [comment]
thanks @sandroacoelho :)

**Comment by jnehring** [comment]
@ArneBinder please do research about this configuration option and check if this can improve the stability of FREME NER.

**Comment by Katsivelisp** [comment]
Hi guys,

I don't know if this is related really, but FREME NER has been a bit unstable for the past 2 or 3 days. We get Gateway 502 errors a lot and the service is down for hours during the day.

**Comment by m1ci** [comment]
Are you using FREME NER live or dev?
@jnehring is doing architecture update and FREME NER dev is unstable these days.

**Comment by Katsivelisp** [comment]
We use FREME dev. Should we go for the live one?

**Comment by m1ci** [comment]
FREME dev is dev (unstable) version :)
We try to keep it as stable as possible, but when we test some new feature, it might be down for some time

We strongly recommend use of FREME live in your production systems.

**Comment by Katsivelisp** [comment]
Well, we do use the live version for our production systems, but we want to test the most recent developments, so that I can come back to you with the dataset we were talking about. Anyway, point taken, we will use FREME live. :)

**Comment by jnehring** [comment]
Im currently working on #43 and so FREME NER does not work on freme-dev right now.

**Comment by jnehring** [comment]
freme-ner should work now on freme-dev

**Comment by ArneBinder** [comment]
`akka.jvm-exit-on-fatal-error ` can be disabled easily, see [this](http://stackoverflow.com/a/34650144) and 
[akka configuration reference](http://doc.akka.io/docs/akka/current/general/configuration.html#akka-actor) for a (really) short description. Should we do so? I think in general it is not recommended, `akka.jvm-exit-on-fatal-error = on` should prevent inconsistent states.

**Comment by jnehring** [comment]
The setting is discouraged. Also the error did not appear in the last weeks. We can still consider using this configuration option when the bug comes back. I think we fixed it.
