### ISSUE TITLE
Add dataset security

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#85]
Please add dataset security to FREME NER. I think you cannot use the managed resource controller. I suggest this approach:

* Access level logic should be equivalent to the other protected resources (visibility public or private, read / write rights according to this)
* FREME NER uses the DatasetSimple database entity. Add a field "user" and a field "visibility" to this entity. This field is optional. When FREME NER writes a dataset to the database it leaves these fields empty.
* When creating a dataset, user and visibility will be entered in the Java code, after the Scala code has been executed.
* Before enrichment, read, update, delete dataset, the access will be checked by the user.
* Delete the other database entity.

**Comment by ArneBinder** [comment]
Implemented dataset management security. The table is called `dataset_metadata`.

TODO: 
 * fix database on freme-dev
 * implement dataset security for POST /e-entity/freme-ner/documents

**Comment by jnehring** [comment]
added table manually. wait for acl problems.

**Comment by jnehring** [comment]
The "ACL Problem" from #86 should be fixed now.

**Comment by ArneBinder** [comment]
implemented.
TODO: testing

**Comment by ArneBinder** [comment]
Dataset management does not work because of https://github.com/freme-project/basic-services/issues/36

**Comment by ArneBinder** [comment]
fixed. Can we close this?

**Comment by jnehring** [comment]
Waiting for #89, #90

**Comment by jnehring** [comment]
This works now
