### ISSUE TITLE
POST dataset dublicate names

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#89]
When I create a dataset and then to the same call again then the triples get added. Instead it should throw an error message `Dataset "name" already exists.` and response code 400.

**Comment by m1ci** [comment]
spotted the same behaviour today.
If POST + existing name -> Dataset "name" already exists.
If PUT + existing name -> update fields (name, description, etc.) + append the entities (if sent any) to the dataset

If I read well the code in https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerManageDatasets.java
PUT is not implemented.
Note that it was in the pre-architecture update, and it was working as described above.

**Comment by ArneBinder** [comment]
Should be fixed. Please recheck.

>PUT is not implemented.

This should be implemented, it's done by [this function](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerManageDatasets.java#L65-L128). @m1ci what kind of (wrong) behaviour did you notice?

**Comment by ArneBinder** [comment]
I see, there is no possibility to change the identifier (name) of a dataset. Should we implement this? How was this done before the architecture update?

**Comment by m1ci** [comment]
The name, is a unique ID for the dataset. So please leave it as it is. 

> Was this possible before the architecture update?

No it was not possible.

**Comment by m1ci** [comment]
@ArneBinder 

> This should be implemented, it's done by this function. @m1ci what kind of (wrong) behaviour did you notice?

PUT does not seem to be implemented (or I do smth wrong)
I try to submit PUT request
`  
curl -X PUT --header "Content-Type: text/n3" --header "Accept: application/json" --header "X-Auth-Token: XXXXXXX" -d @data.nt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?informat=turtle&name=mycooldata1&description=bla&language=en&visibility=public"
`
and I get 
`
{
   "timestamp":1461049917726,
   "status":405,
   "error":"Method Not Allowed",
   "exception":"org.springframework.web.HttpRequestMethodNotSupportedException",
   "message":"Request method 'PUT' not supported","path":"/e-entity/freme-ner/datasets"
}
`

**Comment by m1ci** [comment]
it works, I used wrong URI, sorry for the noise.

**Comment by jnehring** [comment]
I tested again and it works. Thanks
