### ISSUE TITLE
Adding rdfs:label to FREME NERs output

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#92]

**Comment by jnehring** [comment]
We will choose a pipelining approach to create this functionality.  First we will implement this functionality for the dbpedia dataset. There are three subtasks: #97, #98 and #99

**Comment by jnehring** [comment]
Subtasks #97, #98 finished.
When this task is finished, we need to update the SPARQL filter also to output the label also.

**Comment by m1ci** [comment]
> When this task is finished, we need to update the SPARQL filter also to output the label also.

Maybe its better to create new filter instead of updating the current, so that it not crash the wripl client

**Comment by ArneBinder** [comment]
> Maybe its better to create new filter instead of updating the current, so that it not crash the wripl client.

good idea. We will extend the filter "entities-detailed-info" with the label and create a new filter.

**Comment by xFran** [comment]
> Maybe its better to create new filter instead of updating the current, so that it not crash the wripl client.
Or better, ask @xFran first

I'm using anchorOf right now. While this is not removed or the position in the json structure of the anchorOf is not changed you're free to add anything you want.

**Comment by ArneBinder** [comment]
The following request gives the required result:

```
curl -X POST -H "Content-Type: application/json" -d '[
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-entity/freme-ner/documents",
      "parameters": {
        "language": "en",
        "dataset": "dbpedia"
      },
      "headers": {
        "content-type": "text/plain",
        "accept": "text/turtle"
      },
      "body": "This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium."
    },
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-link/documents/",
      "parameters": {
        "templateid": "4496",
        "filter": "entities-detailed-info-label"
      },
      "headers": {
        "content-type": "text/turtle"
      }
    }
  ]
' "http://api.freme-project.eu/current/pipelining/chain"
```

Please replace the value of the first body element (`"This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium."`) with your own input.

**Comment by jnehring** [comment]
This feature is implemented. @koidl @xFran please test it.

**Comment by xFran** [comment]
@jnehring Today I will take a look. Thanks

**Comment by xFran** [comment]
How can I get json instead CSV?

Doing something like this:

"@graph": [
    {
      "@id": "http://freme-project.eu/#char=0,4",
      "@type": [
        "nif:Word",
        "nif:RFC5147String",
        "nif:Phrase",
        "nif:String"
      ],
      **"label": "Belgium", <- NOTE: "label"**
      "nif:anchorOf": "Belgium",
      "beginIndex": "0",
      "endIndex": "4",
      "referenceContext": "http://freme-project.eu/#char=0,60",
      "taClassRef": [
        "http://dbpedia.org/ontology/Settlement",
        "http://nerd.eurecom.fr/ontology#Location",
        "http://dbpedia.org/ontology/PopulatedPlace",
        "http://dbpedia.org/ontology/Location",
        "http://dbpedia.org/ontology/Place"
      ],
      "itsrdf:taConfidence": 0.6771988298358287,
      "taIdentRef": "dbpedia:Belgium"
    },

Would this not be possible?

I'm expecting this kind of result. We use in our application labels like "nif:anchorOf", "beginIndex", "endIndex", "itsrdf:taConfidence", "taIdentRef".
We need those values otherwise either I have to change the entire application or I will break something and believe me due to the complexity it's so easy to brake it. :-) 

Please let me know what do you think. @jnehring @m1ci 

Thank you.

**Comment by jnehring** [comment]
@xFran I modified the pipeline: Now it does not use the filter and uses output format json-ld. Please test if this is the pipeline you need:

```
[
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-entity/freme-ner/documents",
      "parameters": {
        "language": "en",
        "dataset": "dbpedia"
      },
      "headers": {
        "content-type": "text/plain",
        "accept": "text/turtle"
      },
      "body": "This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium."
    },
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-link/documents/",
      "parameters": {
        "templateid": "4496"
      },
      "headers": {
        "content-type": "text/turtle",
        "accept": "application/json+ld"
      }
    }
  ]
```

**Comment by xFran** [comment]
If the content has new lines "\n" I get "eu.freme.common.exception.InternalServerErrorException" exception.

**Comment by jnehring** [comment]
> If the content has new lines "\n" I get "eu.freme.common.exception.InternalServerErrorException" exception.
Is this normal?

No this is not normal. It is a bug. @ArneBinder will take a look at the bug.

**Comment by ArneBinder** [comment]
@xFran This behaviour is correct. New lines have to be escaped, otherwise this is no valid json. You can check your input with [this validator](http://jsonlint.com/), for instance. If you do not want to escape the new lines by your own, upload the pipeline via [Pipelining --> POST /pipelining/templates](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/pipelining/post_pipelining_templates) at the api-doc. Then you can use this pipeline with [POST /pipelining/chain/{pipeline-id}](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/pipelining/post_pipelining_chain_id) (instead of POST /pipelining/chain) and submit any text as POST body.

**Comment by xFran** [comment]
@ArneBinder Thanks. Don't worry. I'm removing new lines in my side from the content. I just used Postman and I got that exception.
