### ISSUE TITLE
Add annotation unit to freme ners output

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#93]
FREME NER should have the ability to output annotation units instead of its current output. There will be a parameter "ner-output-format" which can be set to "annotation-unit" or "simple", with "simple" being the default value. "simple" is the behaviour right now. "annotation-unit" changes the output format to the new NIF 2.1 way of representing annotations in annotation units.

We will implement this feature when #92 is finished

**Comment by m1ci** [comment]
IMO having parameter with name `ner-output-format` is bit misleading. A developer might be confused with the two similar parameters `outformat` and `ner-output-format`
Lets think of explanatory name.

Putting @neradis in the loop. Markus, in FREME we want to provide support for NIF with and without annotation units. What do you suggest, what is the best way to handle this? Using a parameter, or?

**Comment by jnehring** [comment]
another idea would be to use a SPARQL filter that converts from NIF 2.0 to NIF 2.1. This can be a more generic solution that can be applied to all e-Services. Then you have to use a pipeline to convert.

**Comment by jnehring** [comment]
this is done
