### ISSUE TITLE
freme ner produces two times "nif:isString"

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#94]
This API call

http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text&outformat=turtle&input=Temple%20Bar%0A%0A%22A%20wonderful%20journey

sends this text to FREME NER

```
Temple Bar

"A wonderful journey
```

and produces this NIF (among other):

```

            <http://freme-project.eu/#char=0,33>
        a               nif:RFC5147String , nif:Context , nif:String ;
        nif:beginIndex  "0"^^xsd:int ;
        nif:endIndex    "33"^^xsd:int ;
        nif:isString    "Temple Bar\n\n\\\"A wonderful journey"^^xsd:string .

                <http://freme-project.eu/#char=0,32>
        a               nif:RFC5147String , nif:Context , nif:String ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "32"^^xsd:nonNegativeInteger ;
        nif:isString    "Temple Bar\n\n\"A wonderful journey" .
```

There are two nif:isString with different length. I think this is caused by the architecture update.

**Comment by jnehring** [comment]
@ArneBinder please solve this issue in pair programming with @bgrusdt

**Comment by ArneBinder** [comment]
@jnehring this should be fixed. Can we close this issue?

**Comment by jnehring** [comment]
The issue is fixed. Thank you!
