### ISSUE TITLE
freme ner hyphen problems

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#95]
Sending this text to FREME NER with this URL

```
“Super performance, most enjoyable” James Joyce Tower, Sandycove.

“Simply Brilliant” Charlie Byrne’s Bookshop, Galway.

“Ulysses brought to life. I felt I was strolling alongside Bloom” Stone House Bookshop, Kilkenny.

“Loved to see the characters come to life” Bookworm Bookshop, Thurles.

“I’m now looking forward to re-opening the book after many, many years” Valley House, Achill.

“Very entertaining, especially for a Joyce novice” Bridge Street Books, Wicklow.

“Splendid way of telling the story of Ulysses” Rathgar Bookshop.

“Wonderful evening and vivid portrayal of so many characters” Barker & Jones, Naas.
```

produces these annotations (among others):

```
<http://freme-project.eu/#char=287,318>
        a                     nif:Phrase , nif:String , nif:Word , nif:RFC5147String ;
        nif:anchorOf          "Simply Brilliant '' Charlie Byrne"^^xsd:string ;
        nif:beginIndex        "287"^^xsd:int ;
        nif:endIndex          "318"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,863> ;
        itsrdf:taClassRef     <http://nerd.eurecom.fr/ontology#Person> ;
        itsrdf:taConfidence   "0.7876513888020594"^^xsd:double .

<http://freme-project.eu/#char=651,672>
        a                     nif:RFC5147String , nif:String , nif:Phrase , nif:Word ;
        nif:anchorOf          "'' Bridge Street Books"^^xsd:string ;
        nif:beginIndex        "651"^^xsd:int ;
        nif:endIndex          "672"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,863> ;
        itsrdf:taClassRef     <http://nerd.eurecom.fr/ontology#Location> ;
        itsrdf:taConfidence   "0.7021040116094527"^^xsd:double .

<http://freme-project.eu/#char=398,425>
        a                     nif:RFC5147String , nif:String , nif:Word , nif:Phrase ;
        nif:anchorOf          "Bloom '' Stone House Bookshop"^^xsd:string ;
        nif:beginIndex        "398"^^xsd:int ;
        nif:endIndex          "425"^^xsd:int ;
        nif:referenceContext  <http://freme-project.eu/#char=0,863> ;
        itsrdf:taClassRef     <http://www.w3.org/2002/07/owl#Thing> ;
        itsrdf:taConfidence   "0.7807868972156667"^^xsd:double .
```

The problem is that the double quote character is converted to two single quotes. It should stay double quote.

**Comment by jnehring** [comment]
In last developers call we agreed that @m1ci or @sandroacoelho will take a look at this.

**Comment by sandroacoelho** [comment]
Hi all,

We are leverage in Solr results (for mentions) instead of use the original text. It can "create" new 
characters like [here](https://github.com/freme-project/freme-ner/blob/2f538019c60f3c05107b4bf8ba93f4f243f45a85/src/main/java/org/elinker/core/api/java/serialize/NIFConverter.java#L84) and [here](https://github.com/freme-project/freme-ner/blob/2f538019c60f3c05107b4bf8ba93f4f243f45a85/src/main/java/org/elinker/core/api/java/serialize/NIFConverter.java#L85), or sometimes put new spaces, single quotes etc.

I am changing this approach to use the original. Please give me one more business day to change and test it.

**Comment by jnehring** [comment]
Thanks @sandroacoelho . The code you mention says that this is a "temporary fix for ttps://github.com/freme-project/e-Entity/issues/57". So when you finished coding we should test that ttps://github.com/freme-project/e-Entity/issues/57 is not back

**Comment by jnehring** [comment]
any news here, @sandroacoelho  ?

**Comment by sandroacoelho** [comment]
Hi @jnehring: I am doing my final tests. I intend to commit tomorrow

**Comment by sandroacoelho** [comment]
Hi @jnehring, @m1ci . Sorry for the big delay. 
Fixed. When are you testing  #95 and #95,  could you please include #57 too?   Thanks.

**Comment by jnehring** [comment]
Problem fixed. Thanks
