### ISSUE TITLE
Upload datasets to FREME triplestore

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#97]
Upload the datasets we need for the rdfs:label feature (#92) to our FREME triplestore. Only triples with rdfs:label property should be uploaded to FREME NER.

I think first we need the english DBPedia. We still need to consider whether more datasets are required.

**Comment by jnehring** [comment]
@bgrusdt please create the dataset first
* Download the dbpedia english dump.
* Write a script that extracts all triples with english labels. Labels can be expressed via rdfs:label but also via other properties, e.g. foaf:name or skos:prefLabel. Please create a list of label properties.
* The dataset can contain many labels for one resource but we need only one label.

**Comment by jnehring** [comment]
This will be implemented by @m1ci

**Comment by jnehring** [comment]
finished in #98

**Comment by m1ci** [comment]
I have uploaded the DBpedia labels (english only) to our FREME triplestore.
The labels dataset is loaded in the http://www.freme-project.eu/datasets/dbpedia-labels graph
