### ISSUE TITLE
fetch label e-link template

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#98]
Please create a template to fetch rdfs:label for all entities linked by FREME NER for the dbpedia dataset. It uses the dbpedia subset created in #97 and the FREME triplestore. Maybe a similar template has been created in #62.

This template should return only one label. Preferably the same label when called several times for the same link.

This features waits for #97.

**Comment by m1ci** [comment]
I have created template with ID 4496 which retrieves rdfs:label for DBpedia resource.
The template is using the DBpedia SPARQL endpoint.
As soon as we load the data into the FREME triple store, I'll update the template and switch the endpoint.

**Comment by jnehring** [comment]
Thanks milan. I will create the pipeline in #99

**Comment by m1ci** [comment]
@jnehring  The DBpedia labels are loaded in the FREME triplestore. I have also updated the template with ID 4496 so it is now using the FREME triplestore template.

**Comment by jnehring** [comment]
Thank you. I will create the pipeline (see #99)
