### ISSUE TITLE
Create pipeline freme-ner and e-link

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#99]
Please create a pipeline that

1) calls freme ner with language=en, dataset=dbpedia
2) calls the template created in #98
3) calls a SPARQL filter similar to entities-detailed-info which returns all information of entities-detailed-info + the new label. This SPARQL filter needs to be created.

So the result of the pipeline is the results of freme-ner + the rdfs:label property for each dbpedia link.

This feature waits for #97 and #98.

**Comment by m1ci** [comment]
the template is created, it has id 4496

**Comment by jnehring** [comment]
done. see #92
